 CREATE TABLE IF NOT EXISTS players (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  lobby_id UUID REFERENCES lobbies(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT now(),
  is_imposter BOOLEAN DEFAULT false,
  votes integer DEFAULT 0 NOT NULL,
  assigned_word TEXT
);




CREATE TABLE IF NOT EXISTS lobbies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    code TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT now(),
    imposter_knows BOOLEAN 
);


CREATE TABLE word_pairs (
id UUID PRIMARY KEY
category TEXT,
real_word TEXT,
imposter_word TEXT
);


-- Generated words 
-- put into a insert query
INSERT INTO word_pairs (id, category, real_word, imposter_word) VALUES
(gen_random_uuid(), 'Professions', 'Singer', 'Microphone'),
(gen_random_uuid(), 'Professions', 'Dancer', 'Ballet'),
(gen_random_uuid(), 'Professions', 'Actor', 'Stage'),
(gen_random_uuid(), 'Professions', 'Comedian', 'Joke'),
(gen_random_uuid(), 'Professions', 'Writer', 'Novel'),
(gen_random_uuid(), 'Professions', 'Journalist', 'Article'),
(gen_random_uuid(), 'Professions', 'Reporter', 'News'),
(gen_random_uuid(), 'Professions', 'Editor', 'Revision'),
(gen_random_uuid(), 'Professions', 'Librarian', 'Books'),
(gen_random_uuid(), 'Professions', 'Accountant', 'Tax'),
(gen_random_uuid(), 'Professions', 'Banker', 'Vault'),
(gen_random_uuid(), 'Professions', 'Cashier', 'Register'),
(gen_random_uuid(), 'Professions', 'Salesperson', 'Commission'),
(gen_random_uuid(), 'Professions', 'Real Estate Agent', 'Property'),
(gen_random_uuid(), 'Professions', 'Insurance Agent', 'Policy'),
(gen_random_uuid(), 'Professions', 'Financial Advisor', 'Investment'),
(gen_random_uuid(), 'Professions', 'CEO', 'Executive'),
(gen_random_uuid(), 'Professions', 'Manager', 'Team'),
(gen_random_uuid(), 'Professions', 'Secretary', 'Office'),
(gen_random_uuid(), 'Professions', 'Receptionist', 'Front Desk'),
(gen_random_uuid(), 'Professions', 'HR Manager', 'Hiring'),
(gen_random_uuid(), 'Professions', 'Consultant', 'Advice'),
(gen_random_uuid(), 'Professions', 'Entrepreneur', 'Startup'),
(gen_random_uuid(), 'Professions', 'Investor', 'Stock'),
(gen_random_uuid(), 'Professions', 'Trader', 'Exchange'),
(gen_random_uuid(), 'Professions', 'Economist', 'Market'),
(gen_random_uuid(), 'Professions', 'Psychologist', 'Therapy'),
(gen_random_uuid(), 'Professions', 'Psychiatrist', 'Mental Health'),
(gen_random_uuid(), 'Professions', 'Counselor', 'Guidance'),
(gen_random_uuid(), 'Professions', 'Social Worker', 'Community'),
(gen_random_uuid(), 'Professions', 'Therapist', 'Session'),
(gen_random_uuid(), 'Professions', 'Chiropractor', 'Spine'),
(gen_random_uuid(), 'Professions', 'Physical Therapist', 'Rehabilitation'),
(gen_random_uuid(), 'Professions', 'Nutritionist', 'Diet'),
(gen_random_uuid(), 'Professions', 'Personal Trainer', 'Gym'),
(gen_random_uuid(), 'Professions', 'Coach', 'Training'),
(gen_random_uuid(), 'Professions', 'Referee', 'Whistle'),
(gen_random_uuid(), 'Professions', 'Athlete', 'Competition'),
(gen_random_uuid(), 'Professions', 'Model', 'Runway'),
(gen_random_uuid(), 'Professions', 'Fashion Designer', 'Clothing'),
(gen_random_uuid(), 'Professions', 'Hair Stylist', 'Scissors'),
(gen_random_uuid(), 'Professions', 'Barber', 'Shave'),
(gen_random_uuid(), 'Professions', 'Makeup Artist', 'Cosmetics'),
(gen_random_uuid(), 'Professions', 'Nail Technician', 'Manicure'),
(gen_random_uuid(), 'Professions', 'Massage Therapist', 'Relaxation'),
(gen_random_uuid(), 'Professions', 'Florist', 'Bouquet'),
(gen_random_uuid(), 'Professions', 'Interior Designer', 'Decor'),
(gen_random_uuid(), 'Professions', 'Landscaper', 'Garden'),
(gen_random_uuid(), 'Professions', 'Construction Worker', 'Hard Hat'),
(gen_random_uuid(), 'Professions', 'Miner', 'Coal'),
(gen_random_uuid(), 'Professions', 'Logger', 'Forest'),
(gen_random_uuid(), 'Professions', 'Truck Driver', 'Highway'),
(gen_random_uuid(), 'Professions', 'Taxi Driver', 'Cab'),
(gen_random_uuid(), 'Professions', 'Bus Driver', 'Route'),
(gen_random_uuid(), 'Professions', 'Train Conductor', 'Railroad'),
(gen_random_uuid(), 'Professions', 'Ship Captain', 'Vessel'),
(gen_random_uuid(), 'Professions', 'Sailor', 'Navy'),
(gen_random_uuid(), 'Professions', 'Soldier', 'Army'),
(gen_random_uuid(), 'Professions', 'General', 'Military'),
(gen_random_uuid(), 'Professions', 'Security Guard', 'Patrol'),
(gen_random_uuid(), 'Professions', 'Detective', 'Investigation'),
(gen_random_uuid(), 'Professions', 'FBI Agent', 'Bureau'),
(gen_random_uuid(), 'Professions', 'Spy', 'Undercover'),
(gen_random_uuid(), 'Professions', 'Bodyguard', 'Protection'),
(gen_random_uuid(), 'Professions', 'Bouncer', 'Nightclub'),
(gen_random_uuid(), 'Professions', 'Locksmith', 'Key'),
(gen_random_uuid(), 'Professions', 'Janitor', 'Mop'),
(gen_random_uuid(), 'Professions', 'Housekeeper', 'Clean'),
(gen_random_uuid(), 'Professions', 'Maid', 'Service'),
(gen_random_uuid(), 'Professions', 'Butler', 'Manor'),
(gen_random_uuid(), 'Professions', 'Nanny', 'Childcare'),
(gen_random_uuid(), 'Professions', 'Babysitter', 'Kids'),
(gen_random_uuid(), 'Professions', 'Daycare Worker', 'Toddler'),
(gen_random_uuid(), 'Professions', 'Crossing Guard', 'Stop Sign'),
(gen_random_uuid(), 'Professions', 'Mailman', 'Delivery'),
(gen_random_uuid(), 'Professions', 'Courier', 'Package'),
(gen_random_uuid(), 'Professions', 'Delivery Driver', 'Amazon'),
(gen_random_uuid(), 'Professions', 'Warehouse Worker', 'Forklift'),
(gen_random_uuid(), 'Professions', 'Factory Worker', 'Assembly Line'),
(gen_random_uuid(), 'Professions', 'Quality Control', 'Inspector'),
(gen_random_uuid(), 'Professions', 'Welder', 'Torch'),
(gen_random_uuid(), 'Professions', 'Machinist', 'Lathe'),
(gen_random_uuid(), 'Professions', 'Blacksmith', 'Anvil'),
(gen_random_uuid(), 'Professions', 'Jeweler', 'Diamond'),
(gen_random_uuid(), 'Professions', 'Watchmaker', 'Gears'),
(gen_random_uuid(), 'Professions', 'Tailor', 'Sewing'),
(gen_random_uuid(), 'Professions', 'Cobbler', 'Shoes'),
(gen_random_uuid(), 'Professions', 'Leather Worker', 'Hide'),
(gen_random_uuid(), 'Professions', 'Butcher', 'Meat'),
(gen_random_uuid(), 'Professions', 'Fishmonger', 'Seafood'),
(gen_random_uuid(), 'Professions', 'Grocer', 'Produce'),
(gen_random_uuid(), 'Professions', 'Sommelier', 'Wine'),
(gen_random_uuid(), 'Professions', 'Brewer', 'Beer'),
(gen_random_uuid(), 'Professions', 'Distiller', 'Whiskey'),
(gen_random_uuid(), 'Professions', 'Vintner', 'Vineyard'),
(gen_random_uuid(), 'Professions', 'Zookeeper', 'Animals'),
(gen_random_uuid(), 'Professions', 'Dog Walker', 'Leash'),
(gen_random_uuid(), 'Professions', 'Pet Groomer', 'Shampoo'),
(gen_random_uuid(), 'Professions', 'Animal Trainer', 'Tricks'),
(gen_random_uuid(), 'Professions', 'Park Ranger', 'Nature'),
(gen_random_uuid(), 'Professions', 'Tour Guide', 'Sightseeing'),
(gen_random_uuid(), 'Professions', 'Travel Agent', 'Vacation'),
(gen_random_uuid(), 'Professions', 'Hotel Manager', 'Hospitality'),
(gen_random_uuid(), 'Professions', 'Concierge', 'Lobby'),
(gen_random_uuid(), 'Professions', 'Event Planner', 'Wedding'),
(gen_random_uuid(), 'Professions', 'Caterer', 'Food Service'),
(gen_random_uuid(), 'Professions', 'DJ', 'Music'),
(gen_random_uuid(), 'Professions', 'Sound Engineer', 'Audio'),
(gen_random_uuid(), 'Professions', 'Lighting Technician', 'Stage'),
(gen_random_uuid(), 'Professions', 'Stagehand', 'Crew'),
(gen_random_uuid(), 'Professions', 'Stunt Double', 'Dangerous'),
(gen_random_uuid(), 'Professions', 'Voice Actor', 'Dubbing'),
(gen_random_uuid(), 'Professions', 'Animator', 'Cartoon'),
(gen_random_uuid(), 'Professions', 'Illustrator', 'Drawing'),
(gen_random_uuid(), 'Professions', 'Tattoo Artist', 'Ink'),
(gen_random_uuid(), 'Professions', 'Piercer', 'Body Modification'),
(gen_random_uuid(), 'Professions', 'Auctioneer', 'Gavel'),
(gen_random_uuid(), 'Professions', 'Appraiser', 'Valuation'),
(gen_random_uuid(), 'Professions', 'Archaeologist', 'Dig'),
(gen_random_uuid(), 'Professions', 'Paleontologist', 'Fossil'),
(gen_random_uuid(), 'Professions', 'Anthropologist', 'Culture'),
(gen_random_uuid(), 'Professions', 'Historian', 'Archive'),
(gen_random_uuid(), 'Professions', 'Curator', 'Museum'),
(gen_random_uuid(), 'Professions', 'Archivist', 'Records'),
(gen_random_uuid(), 'Professions', 'Translator', 'Language'),
(gen_random_uuid(), 'Professions', 'Interpreter', 'Sign Language'),
(gen_random_uuid(), 'Professions', 'Diplomat', 'Embassy'),
(gen_random_uuid(), 'Professions', 'Ambassador', 'Foreign'),
(gen_random_uuid(), 'Professions', 'Politician', 'Campaign'),
(gen_random_uuid(), 'Professions', 'Senator', 'Congress'),
(gen_random_uuid(), 'Professions', 'Mayor', 'City'),
(gen_random_uuid(), 'Professions', 'Governor', 'State'),
(gen_random_uuid(), 'Professions', 'President', 'White House'),
(gen_random_uuid(), 'Professions', 'Lobbyist', 'Influence'),
(gen_random_uuid(), 'Professions', 'Campaign Manager', 'Election'),
(gen_random_uuid(), 'Professions', 'Pollster', 'Survey'),
(gen_random_uuid(), 'Professions', 'Speechwriter', 'Address'),
(gen_random_uuid(), 'Professions', 'Public Relations', 'PR'),
(gen_random_uuid(), 'Professions', 'Marketing Manager', 'Brand'),
(gen_random_uuid(), 'Professions', 'Advertiser', 'Commercial'),
(gen_random_uuid(), 'Professions', 'Copywriter', 'Slogan'),
(gen_random_uuid(), 'Professions', 'Social Media Manager', 'Engagement'),
(gen_random_uuid(), 'Professions', 'Data Analyst', 'Statistics'),
(gen_random_uuid(), 'Professions', 'Data Scientist', 'Algorithm'),
(gen_random_uuid(), 'Professions', 'IT Specialist', 'Support'),
(gen_random_uuid(), 'Professions', 'Network Administrator', 'Server'),
(gen_random_uuid(), 'Professions', 'Cybersecurity Expert', 'Hacker'),
(gen_random_uuid(), 'Professions', 'Systems Analyst', 'Infrastructure'),
(gen_random_uuid(), 'Professions', 'Database Administrator', 'SQL'),
(gen_random_uuid(), 'Professions', 'UX Designer', 'User Experience'),
(gen_random_uuid(), 'Professions', 'UI Designer', 'Interface'),
(gen_random_uuid(), 'Professions', 'Product Manager', 'Development'),
(gen_random_uuid(), 'Professions', 'Project Manager', 'Timeline'),
(gen_random_uuid(), 'Professions', 'Scrum Master', 'Agile'),
(gen_random_uuid(), 'Professions', 'Business Analyst', 'Requirements'),
(gen_random_uuid(), 'Professions', 'Actuary', 'Risk'),
(gen_random_uuid(), 'Professions', 'Statistician', 'Data'),
(gen_random_uuid(), 'Professions', 'Meteorologist', 'Forecast'),
(gen_random_uuid(), 'Professions', 'Seismologist', 'Earthquake'),
(gen_random_uuid(), 'Professions', 'Oceanographer', 'Marine'),
(gen_random_uuid(), 'Professions', 'Geologist', 'Mineral'),
(gen_random_uuid(), 'Professions', 'Botanist', 'Flora'),
(gen_random_uuid(), 'Professions', 'Zoologist', 'Fauna'),
(gen_random_uuid(), 'Professions', 'Ecologist', 'Environment'),
(gen_random_uuid(), 'Professions', 'Environmental Scientist', 'Conservation'),
(gen_random_uuid(), 'Professions', 'Forester', 'Trees'),
(gen_random_uuid(), 'Professions', 'Wildlife Biologist', 'Species'),
(gen_random_uuid(), 'Professions', 'Marine Biologist', 'Ocean'),
(gen_random_uuid(), 'Professions', 'Microbiologist', 'Bacteria'),
(gen_random_uuid(), 'Professions', 'Geneticist', 'Genes'),
(gen_random_uuid(), 'Professions', 'Virologist', 'Virus'),
(gen_random_uuid(), 'Professions', 'Immunologist', 'Antibodies'),
(gen_random_uuid(), 'Professions', 'Neurologist', 'Brain'),
(gen_random_uuid(), 'Professions', 'Cardiologist', 'Heart'),
(gen_random_uuid(), 'Professions', 'Oncologist', 'Cancer'),
(gen_random_uuid(), 'Professions', 'Pediatrician', 'Children'),
(gen_random_uuid(), 'Professions', 'Obstetrician', 'Pregnancy'),
(gen_random_uuid(), 'Professions', 'Gynecologist', 'Women'),
(gen_random_uuid(), 'Professions', 'Dermatologist', 'Skin'),
(gen_random_uuid(), 'Professions', 'Ophthalmologist', 'Eyes'),
(gen_random_uuid(), 'Professions', 'Optometrist', 'Glasses'),
(gen_random_uuid(), 'Professions', 'Orthodontist', 'Braces'),
(gen_random_uuid(), 'Professions', 'Radiologist', 'X-Ray'),
(gen_random_uuid(), 'Professions', 'Anesthesiologist', 'Surgery'),
(gen_random_uuid(), 'Professions', 'Pathologist', 'Autopsy'),
(gen_random_uuid(), 'Professions', 'Coroner', 'Death'),
(gen_random_uuid(), 'Professions', 'Mortician', 'Funeral'),
(gen_random_uuid(), 'Professions', 'Embalmer', 'Preservation'),

-- HOUSEHOLD & EVERYDAY OBJECTS (500 pairs)
(gen_random_uuid(), 'Household', 'Bed', 'Mattress'),
(gen_random_uuid(), 'Household', 'Pillow', 'Pillowcase'),
(gen_random_uuid(), 'Household', 'Blanket', 'Comforter'),
(gen_random_uuid(), 'Household', 'Sheet', 'Bedding'),
(gen_random_uuid(), 'Household', 'Alarm Clock', 'Snooze'),
(gen_random_uuid(), 'Household', 'Lamp', 'Light Bulb'),
(gen_random_uuid(), 'Household', 'Ceiling Fan', 'Blade'),
(gen_random_uuid(), 'Household', 'Curtain', 'Window'),
(gen_random_uuid(), 'Household', 'Blinds', 'Shade'),
(gen_random_uuid(), 'Household', 'Rug', 'Carpet'),
(gen_random_uuid(), 'Household', 'Couch', 'Sofa'),
(gen_random_uuid(), 'Household', 'Chair', 'Seat'),
(gen_random_uuid(), 'Household', 'Table', 'Surface'),
(gen_random_uuid(), 'Household', 'Desk', 'Work'),
(gen_random_uuid(), 'Household', 'Dresser', 'Drawer'),
(gen_random_uuid(), 'Household', 'Closet', 'Wardrobe'),
(gen_random_uuid(), 'Household', 'Mirror', 'Reflection'),
(gen_random_uuid(), 'Household', 'Picture Frame', 'Photo'),
(gen_random_uuid(), 'Household', 'Clock', 'Time'),
(gen_random_uuid(), 'Household', 'Calendar', 'Date'),
(gen_random_uuid(), 'Household', 'Thermostat', 'Temperature'),
(gen_random_uuid(), 'Household', 'Smoke Detector', 'Battery'),
(gen_random_uuid(), 'Household', 'Door', 'Doorknob'),
(gen_random_uuid(), 'Household', 'Window', 'Glass'),
(gen_random_uuid(), 'Household', 'Lock', 'Key'),
(gen_random_uuid(), 'Household', 'Hinge', 'Swing'),
(gen_random_uuid(), 'Household', 'Light Switch', 'Toggle'),
(gen_random_uuid(), 'Household', 'Outlet', 'Socket'),
(gen_random_uuid(), 'Household', 'Extension Cord', 'Plug'),
(gen_random_uuid(), 'Household', 'Power Strip', 'Surge Protector'),
(gen_random_uuid(), 'Household', 'Broom', 'Sweep'),
(gen_random_uuid(), 'Household', 'Mop', 'Bucket'),
(gen_random_uuid(), 'Household', 'Dustpan', 'Dirt'),
(gen_random_uuid(), 'Household', 'Trash Can', 'Garbage'),
(gen_random_uuid(), 'Household', 'Recycling Bin', 'Plastic'),
(gen_random_uuid(), 'Household', 'Laundry Basket', 'Hamper'),
(gen_random_uuid(), 'Household', 'Iron', 'Wrinkle'),
(gen_random_uuid(), 'Household', 'Ironing Board', 'Press'),
(gen_random_uuid(), 'Household', 'Clothes Hanger', 'Closet'),
(gen_random_uuid(), 'Household', 'Step Stool', 'Ladder'),
(gen_random_uuid(), 'Household', 'Toolbox', 'Tools'),
(gen_random_uuid(), 'Household', 'Screwdriver', 'Screw'),
(gen_random_uuid(), 'Household', 'Hammer', 'Nail'),
(gen_random_uuid(), 'Household', 'Wrench', 'Bolt'),
(gen_random_uuid(), 'Household', 'Pliers', 'Grip'),
(gen_random_uuid(), 'Household', 'Tape Measure', 'Length'),
(gen_random_uuid(), 'Household', 'Level', 'Straight'),
(gen_random_uuid(), 'Household', 'Drill', 'Hole'),
(gen_random_uuid(), 'Household', 'Saw', 'Cut'),
(gen_random_uuid(), 'Household', 'Sandpaper', 'Smooth'),
(gen_random_uuid(), 'Household', 'Paint Brush', 'Paint'),
(gen_random_uuid(), 'Household', 'Paint Roller', 'Wall'),
(gen_random_uuid(), 'Household', 'Paint Can', 'Color'),
(gen_random_uuid(), 'Kitchen', 'Stove', 'Burner'),
(gen_random_uuid(), 'Kitchen', 'Oven', 'Bake'),
(gen_random_uuid(), 'Kitchen', 'Microwave', 'Heat'),
(gen_random_uuid(), 'Kitchen', 'Refrigerator', 'Cold'),
(gen_random_uuid(), 'Kitchen', 'Freezer', 'Ice'),
(gen_random_uuid(), 'Kitchen', 'Dishwasher', 'Soap'),
(gen_random_uuid(), 'Kitchen', 'Sink', 'Faucet'),
(gen_random_uuid(), 'Kitchen', 'Garbage Disposal', 'Drain'),
(gen_random_uuid(), 'Kitchen', 'Cupboard', 'Cabinet'),
(gen_random_uuid(), 'Kitchen', 'Pantry', 'Storage'),
(gen_random_uuid(), 'Kitchen', 'Counter', 'Granite'),
(gen_random_uuid(), 'Kitchen', 'Cutting Board', 'Chop'),
(gen_random_uuid(), 'Kitchen', 'Knife', 'Sharp'),
(gen_random_uuid(), 'Kitchen', 'Fork', 'Prongs'),
(gen_random_uuid(), 'Kitchen', 'Spoon', 'Scoop'),
(gen_random_uuid(), 'Kitchen', 'Plate', 'Dish'),
(gen_random_uuid(), 'Kitchen', 'Bowl', 'Cereal'),
(gen_random_uuid(), 'Kitchen', 'Cup', 'Mug'),
(gen_random_uuid(), 'Kitchen', 'Glass', 'Drink'),
(gen_random_uuid(), 'Kitchen', 'Pot', 'Cook'),
(gen_random_uuid(), 'Kitchen', 'Pan', 'Fry'),
(gen_random_uuid(), 'Kitchen', 'Skillet', 'Cast Iron'),
(gen_random_uuid(), 'Kitchen', 'Wok', 'Stir Fry'),
(gen_random_uuid(), 'Kitchen', 'Spatula', 'Flip'),
(gen_random_uuid(), 'Kitchen', 'Ladle', 'Soup'),
(gen_random_uuid(), 'Kitchen', 'Whisk', 'Beat'),
(gen_random_uuid(), 'Kitchen', 'Tongs', 'Grab'),
(gen_random_uuid(), 'Kitchen', 'Peeler', 'Skin'),
(gen_random_uuid(), 'Kitchen', 'Grater', 'Shred'),
(gen_random_uuid(), 'Kitchen', 'Strainer', 'Colander'),
(gen_random_uuid(), 'Kitchen', 'Measuring Cup', 'Volume'),
(gen_random_uuid(), 'Kitchen', 'Measuring Spoon', 'Teaspoon'),
(gen_random_uuid(), 'Kitchen', 'Mixing Bowl', 'Stir'),
(gen_random_uuid(), 'Kitchen', 'Baking Sheet', 'Cookie'),
(gen_random_uuid(), 'Kitchen', 'Cake Pan', 'Round'),
(gen_random_uuid(), 'Kitchen', 'Muffin Tin', 'Cupcake'),
(gen_random_uuid(), 'Kitchen', 'Rolling Pin', 'Dough'),
(gen_random_uuid(), 'Kitchen', 'Can Opener', 'Tin'),
(gen_random_uuid(), 'Kitchen', 'Bottle Opener', 'Cap'),
(gen_random_uuid(), 'Kitchen', 'Corkscrew', 'Wine'),
(gen_random_uuid(), 'Kitchen', 'Oven Mitt', 'Hot'),
(gen_random_uuid(), 'Kitchen', 'Pot Holder', 'Heat'),
(gen_random_uuid(), 'Kitchen', 'Apron', 'Cook'),
(gen_random_uuid(), 'Kitchen', 'Dish Towel', 'Dry'),
(gen_random_uuid(), 'Kitchen', 'Sponge', 'Scrub'),
(gen_random_uuid(), 'Kitchen', 'Dish Soap', 'Clean'),
(gen_random_uuid(), 'Kitchen', 'Toaster', 'Bread'),
(gen_random_uuid(), 'Kitchen', 'Blender', 'Smoothie'),
(gen_random_uuid(), 'Kitchen', 'Food Processor', 'Chop'),
(gen_random_uuid(), 'Kitchen', 'Coffee Maker', 'Brew'),
(gen_random_uuid(), 'Kitchen', 'Kettle', 'Boil'),
(gen_random_uuid(), 'Kitchen', 'Slow Cooker', 'Crock Pot'),
(gen_random_uuid(), 'Kitchen', 'Pressure Cooker', 'Instant Pot'),
(gen_random_uuid(), 'Kitchen', 'Air Fryer', 'Crispy'),
(gen_random_uuid(), 'Kitchen', 'Rice Cooker', 'Steam'),
(gen_random_uuid(), 'Kitchen', 'Waffle Maker', 'Grid'),
(gen_random_uuid(), 'Kitchen', 'Mixer', 'Beater'),
(gen_random_uuid(), 'Kitchen', 'Juicer', 'Extract'),
(gen_random_uuid(), 'Kitchen', 'Ice Cream Maker', 'Churn'),
(gen_random_uuid(), 'Kitchen', 'Bread Maker', 'Loaf'),
(gen_random_uuid(), 'Kitchen', 'Electric Grill', 'Indoor'),
(gen_random_uuid(), 'Kitchen', 'Sandwich Press', 'Panini'),
(gen_random_uuid(), 'Kitchen', 'Egg Cooker', 'Boil'),
(gen_random_uuid(), 'Kitchen', 'Food Scale', 'Weight'),
(gen_random_uuid(), 'Kitchen', 'Kitchen Timer', 'Countdown'),
(gen_random_uuid(), 'Kitchen', 'Thermometer', 'Temperature'),
(gen_random_uuid(), 'Kitchen', 'Cookie Cutter', 'Shape'),
(gen_random_uuid(), 'Kitchen', 'Piping Bag', 'Frosting'),
(gen_random_uuid(), 'Kitchen', 'Funnel', 'Pour'),
(gen_random_uuid(), 'Kitchen', 'Salad Spinner', 'Lettuce'),
(gen_random_uuid(), 'Kitchen', 'Garlic Press', 'Crush'),
(gen_random_uuid(), 'Kitchen', 'Lemon Squeezer', 'Juice'),
(gen_random_uuid(), 'Kitchen', 'Pizza Cutter', 'Wheel'),
(gen_random_uuid(), 'Kitchen', 'Meat Tenderizer', 'Mallet'),
(gen_random_uuid(), 'Kitchen', 'Mortar and Pestle', 'Grind'),
(gen_random_uuid(), 'Kitchen', 'Tea Infuser', 'Steep'),
(gen_random_uuid(), 'Kitchen', 'French Press', 'Coffee'),
(gen_random_uuid(), 'Kitchen', 'Espresso Machine', 'Cafe'),
(gen_random_uuid(), 'Bathroom', 'Toilet', 'Flush'),
(gen_random_uuid(), 'Bathroom', 'Sink', 'Basin'),
(gen_random_uuid(), 'Bathroom', 'Bathtub', 'Soak'),
(gen_random_uuid(), 'Bathroom', 'Shower', 'Spray'),
(gen_random_uuid(), 'Bathroom', 'Showerhead', 'Water'),
(gen_random_uuid(), 'Bathroom', 'Faucet', 'Tap'),
(gen_random_uuid(), 'Bathroom', 'Drain', 'Pipe'),
(gen_random_uuid(), 'Bathroom', 'Toilet Paper', 'Roll'),
(gen_random_uuid(), 'Bathroom', 'Towel', 'Dry'),
(gen_random_uuid(), 'Bathroom', 'Hand Towel', 'Small'),
(gen_random_uuid(), 'Bathroom', 'Bath Mat', 'Rug'),
(gen_random_uuid(), 'Bathroom', 'Shower Curtain', 'Plastic'),
(gen_random_uuid(), 'Bathroom', 'Soap', 'Lather'),
(gen_random_uuid(), 'Bathroom', 'Shampoo', 'Hair'),
(gen_random_uuid(), 'Bathroom', 'Conditioner', 'Smooth'),
(gen_random_uuid(), 'Bathroom', 'Body Wash', 'Gel'),
(gen_random_uuid(), 'Geography', 'Texas', 'Houston'),
(gen_random_uuid(), 'Geography', 'California', 'Sacramento'),
(gen_random_uuid(), 'Geography', 'Florida', 'Miami'),
(gen_random_uuid(), 'Geography', 'New York', 'Manhattan'),
(gen_random_uuid(), 'Geography', 'Illinois', 'Chicago'),
(gen_random_uuid(), 'Geography', 'Pennsylvania', 'Philadelphia'),
(gen_random_uuid(), 'Geography', 'Ohio', 'Cleveland'),
(gen_random_uuid(), 'Geography', 'Georgia', 'Savannah'),
(gen_random_uuid(), 'Geography', 'Michigan', 'Detroit'),
(gen_random_uuid(), 'Geography', 'Arizona', 'Phoenix'),
(gen_random_uuid(), 'Geography', 'Massachusetts', 'Boston'),
(gen_random_uuid(), 'Geography', 'Tennessee', 'Nashville'),
(gen_random_uuid(), 'Geography', 'Missouri', 'Kansas City'),
(gen_random_uuid(), 'Geography', 'Maryland', 'Baltimore'),
(gen_random_uuid(), 'Geography', 'Wisconsin', 'Milwaukee'),
(gen_random_uuid(), 'Geography', 'Colorado', 'Denver'),
(gen_random_uuid(), 'Geography', 'Minnesota', 'Minneapolis'),
(gen_random_uuid(), 'Geography', 'South Carolina', 'Charleston'),
(gen_random_uuid(), 'Geography', 'Alabama', 'Montgomery'),
(gen_random_uuid(), 'Geography', 'Louisiana', 'Baton Rouge'),
(gen_random_uuid(), 'Geography', 'Kentucky', 'Louisville'),
(gen_random_uuid(), 'Geography', 'Oregon', 'Portland'),
(gen_random_uuid(), 'Geography', 'Oklahoma', 'Tulsa'),
(gen_random_uuid(), 'Geography', 'Connecticut', 'Hartford'),
(gen_random_uuid(), 'Geography', 'Iowa', 'Des Moines'),
(gen_random_uuid(), 'Geography', 'Utah', 'Salt Lake City'),
(gen_random_uuid(), 'Geography', 'Nevada', 'Las Vegas'),
(gen_random_uuid(), 'Geography', 'Arkansas', 'Little Rock'),
(gen_random_uuid(), 'Geography', 'Mississippi', 'Jackson'),
(gen_random_uuid(), 'Geography', 'Kansas', 'Wichita'),
(gen_random_uuid(), 'Geography', 'New Mexico', 'Albuquerque'),
(gen_random_uuid(), 'Geography', 'Nebraska', 'Omaha'),
(gen_random_uuid(), 'Geography', 'West Virginia', 'Charleston'),
(gen_random_uuid(), 'Geography', 'Idaho', 'Boise'),
(gen_random_uuid(), 'Geography', 'Hawaii', 'Honolulu'),
(gen_random_uuid(), 'Geography', 'New Hampshire', 'Concord'),
(gen_random_uuid(), 'Geography', 'Maine', 'Augusta'),
(gen_random_uuid(), 'Geography', 'Rhode Island', 'Providence'),
(gen_random_uuid(), 'Geography', 'Montana', 'Billings'),
(gen_random_uuid(), 'Geography', 'Delaware', 'Wilmington'),
(gen_random_uuid(), 'Geography', 'South Dakota', 'Sioux Falls'),
(gen_random_uuid(), 'Geography', 'North Dakota', 'Fargo'),
(gen_random_uuid(), 'Geography', 'Alaska', 'Anchorage'),
(gen_random_uuid(), 'Geography', 'Vermont', 'Burlington'),
(gen_random_uuid(), 'Geography', 'Wyoming', 'Cheyenne'),
(gen_random_uuid(), 'Geography', 'Washington', 'Seattle'),
(gen_random_uuid(), 'Geography', 'Virginia', 'Richmond'),
(gen_random_uuid(), 'Geography', 'North Carolina', 'Charlotte'),
(gen_random_uuid(), 'Geography', 'Indiana', 'Indianapolis'),
(gen_random_uuid(), 'Geography', 'New Jersey', 'Newark'),
(gen_random_uuid(), 'World Geography', 'England', 'London'),
(gen_random_uuid(), 'World Geography', 'France', 'Paris'),
(gen_random_uuid(), 'World Geography', 'Italy', 'Rome'),
(gen_random_uuid(), 'World Geography', 'Spain', 'Madrid'),
(gen_random_uuid(), 'World Geography', 'Germany', 'Berlin'),
(gen_random_uuid(), 'World Geography', 'Japan', 'Tokyo'),
(gen_random_uuid(), 'World Geography', 'China', 'Beijing'),
(gen_random_uuid(), 'World Geography', 'Russia', 'Moscow'),
(gen_random_uuid(), 'World Geography', 'Canada', 'Ottawa'),
(gen_random_uuid(), 'World Geography', 'Australia', 'Sydney'),
(gen_random_uuid(), 'World Geography', 'Brazil', 'Rio'),
(gen_random_uuid(), 'World Geography', 'India', 'Mumbai'),
(gen_random_uuid(), 'World Geography', 'Egypt', 'Cairo'),
(gen_random_uuid(), 'World Geography', 'Greece', 'Athens'),
(gen_random_uuid(), 'World Geography', 'Ireland', 'Dublin'),
(gen_random_uuid(), 'World Geography', 'Scotland', 'Edinburgh'),
(gen_random_uuid(), 'World Geography', 'Netherlands', 'Amsterdam'),
(gen_random_uuid(), 'World Geography', 'Belgium', 'Brussels'),
(gen_random_uuid(), 'World Geography', 'Sweden', 'Stockholm'),
(gen_random_uuid(), 'World Geography', 'Norway', 'Oslo'),
(gen_random_uuid(), 'World Geography', 'Denmark', 'Copenhagen'),
(gen_random_uuid(), 'World Geography', 'Portugal', 'Lisbon'),
(gen_random_uuid(), 'World Geography', 'Switzerland', 'Zurich'),
(gen_random_uuid(), 'World Geography', 'Austria', 'Vienna'),
(gen_random_uuid(), 'World Geography', 'Poland', 'Warsaw'),
(gen_random_uuid(), 'World Geography', 'Czech Republic', 'Prague'),
(gen_random_uuid(), 'World Geography', 'Hungary', 'Budapest'),
(gen_random_uuid(), 'World Geography', 'Turkey', 'Istanbul'),
(gen_random_uuid(), 'World Geography', 'Thailand', 'Bangkok'),
(gen_random_uuid(), 'World Geography', 'Vietnam', 'Hanoi'),
(gen_random_uuid(), 'World Geography', 'South Korea', 'Seoul'),
(gen_random_uuid(), 'World Geography', 'Mexico', 'Cancun'),
(gen_random_uuid(), 'World Geography', 'Argentina', 'Buenos Aires'),
(gen_random_uuid(), 'World Geography', 'Chile', 'Santiago'),
(gen_random_uuid(), 'World Geography', 'Peru', 'Lima'),
(gen_random_uuid(), 'World Geography', 'Colombia', 'Bogota'),
(gen_random_uuid(), 'World Geography', 'Morocco', 'Marrakech'),
(gen_random_uuid(), 'World Geography', 'Kenya', 'Nairobi'),
(gen_random_uuid(), 'World Geography', 'South Africa', 'Cape Town'),
(gen_random_uuid(), 'World Geography', 'New Zealand', 'Auckland'),
(gen_random_uuid(), 'World Geography', 'Singapore', 'Marina Bay'),
(gen_random_uuid(), 'World Geography', 'Malaysia', 'Kuala Lumpur'),
(gen_random_uuid(), 'World Geography', 'Indonesia', 'Jakarta'),
(gen_random_uuid(), 'World Geography', 'Philippines', 'Manila'),
(gen_random_uuid(), 'World Geography', 'Saudi Arabia', 'Riyadh'),
(gen_random_uuid(), 'World Geography', 'United Arab Emirates', 'Dubai'),
(gen_random_uuid(), 'World Geography', 'Israel', 'Jerusalem'),
(gen_random_uuid(), 'World Geography', 'Finland', 'Helsinki'),

-- TECHNOLOGY & INNOVATION (200 pairs)
(gen_random_uuid(), 'Technology', 'Internet', 'Browser'),
(gen_random_uuid(), 'Technology', 'Computer', 'Keyboard'),
(gen_random_uuid(), 'Technology', 'Smartphone', 'Touchscreen'),
(gen_random_uuid(), 'Technology', 'Email', 'Inbox'),
(gen_random_uuid(), 'Technology', 'Website', 'Domain'),
(gen_random_uuid(), 'Technology', 'Software', 'Application'),
(gen_random_uuid(), 'Technology', 'Hardware', 'Motherboard'),
(gen_random_uuid(), 'Technology', 'Database', 'SQL'),
(gen_random_uuid(), 'Technology', 'Cloud', 'Server'),
(gen_random_uuid(), 'Technology', 'WiFi', 'Router'),
(gen_random_uuid(), 'Technology', 'Bluetooth', 'Wireless'),
(gen_random_uuid(), 'Technology', 'Download', 'Upload'),
(gen_random_uuid(), 'Technology', 'Streaming', 'Buffer'),
(gen_random_uuid(), 'Technology', 'Algorithm', 'Code'),
(gen_random_uuid(), 'Technology', 'Programming', 'Debugging'),
(gen_random_uuid(), 'Technology', 'Security', 'Password'),
(gen_random_uuid(), 'Technology', 'Virus', 'Antivirus'),
(gen_random_uuid(), 'Technology', 'Hacker', 'Firewall'),
(gen_random_uuid(), 'Technology', 'Update', 'Patch'),
(gen_random_uuid(), 'Technology', 'Cache', 'Cookies'),
(gen_random_uuid(), 'Technology', 'Pixel', 'Resolution'),
(gen_random_uuid(), 'Technology', 'Battery', 'Charger'),
(gen_random_uuid(), 'Technology', 'Laptop', 'Trackpad'),
(gen_random_uuid(), 'Technology', 'Monitor', 'Display'),
(gen_random_uuid(), 'Technology', 'Printer', 'Ink'),
(gen_random_uuid(), 'Technology', 'Scanner', 'Document'),
(gen_random_uuid(), 'Technology', 'USB', 'Flash Drive'),
(gen_random_uuid(), 'Technology', 'SSD', 'Hard Drive'),
(gen_random_uuid(), 'Technology', 'RAM', 'Memory'),
(gen_random_uuid(), 'Technology', 'CPU', 'Processor'),
(gen_random_uuid(), 'Technology', 'GPU', 'Graphics Card'),
(gen_random_uuid(), 'Technology', 'Screenshot', 'Capture'),
(gen_random_uuid(), 'Technology', 'Backup', 'Restore'),
(gen_random_uuid(), 'Technology', 'Plugin', 'Extension'),
(gen_random_uuid(), 'Technology', 'Notification', 'Alert'),
(gen_random_uuid(), 'Technology', 'Podcast', 'Episode'),
(gen_random_uuid(), 'Technology', 'Emoji', 'Emoticon'),
(gen_random_uuid(), 'Technology', 'GIF', 'Animation'),
(gen_random_uuid(), 'Technology', 'Meme', 'Viral'),
(gen_random_uuid(), 'Technology', 'Hashtag', 'Trending'),
(gen_random_uuid(), 'Technology', 'Selfie', 'Camera'),
(gen_random_uuid(), 'Technology', 'Filter', 'Instagram'),
(gen_random_uuid(), 'Technology', 'Retweet', 'Twitter'),
(gen_random_uuid(), 'Technology', 'Subscribe', 'YouTube'),
(gen_random_uuid(), 'Technology', 'Playlist', 'Spotify'),
(gen_random_uuid(), 'Technology', 'Binge', 'Netflix'),
(gen_random_uuid(), 'Technology', 'Swipe', 'Tinder'),
(gen_random_uuid(), 'Technology', 'Story', 'Snapchat'),
(gen_random_uuid(), 'Technology', 'Thread', 'Reddit'),
(gen_random_uuid(), 'Technology', 'Upvote', 'Downvote'),
(gen_random_uuid(), 'Technology', 'DM', 'Message'),
(gen_random_uuid(), 'Technology', 'Profile', 'Avatar'),
(gen_random_uuid(), 'Technology', 'Follow', 'Follower'),
(gen_random_uuid(), 'Technology', 'Block', 'Mute'),
(gen_random_uuid(), 'Technology', 'Report', 'Flag'),
(gen_random_uuid(), 'Technology', 'Share', 'Forward'),
(gen_random_uuid(), 'Technology', 'Like', 'Heart'),
(gen_random_uuid(), 'Technology', 'Comment', 'Reply'),
(gen_random_uuid(), 'Technology', 'Tag', 'Mention'),
(gen_random_uuid(), 'Technology', 'Bookmark', 'Save'),
(gen_random_uuid(), 'Technology', 'Archive', 'Delete'),
(gen_random_uuid(), 'Technology', 'Settings', 'Preferences'),
(gen_random_uuid(), 'Technology', 'Login', 'Username'),
(gen_random_uuid(), 'Technology', 'Logout', 'Sign Out'),
(gen_random_uuid(), 'Technology', 'Register', 'Sign Up'),
(gen_random_uuid(), 'Technology', 'Verify', 'Captcha'),
(gen_random_uuid(), 'Technology', 'Spam', 'Junk'),
(gen_random_uuid(), 'Technology', 'Attach', 'Attachment'),
(gen_random_uuid(), 'Technology', 'Draft', 'Compose'),
(gen_random_uuid(), 'Technology', 'Inbox', 'Sent'),
(gen_random_uuid(), 'Technology', 'Refresh', 'Reload'),
(gen_random_uuid(), 'Technology', 'Scroll', 'Swipe'),
(gen_random_uuid(), 'Technology', 'Click', 'Double-Click'),
(gen_random_uuid(), 'Technology', 'Drag', 'Drop'),
(gen_random_uuid(), 'Technology', 'Copy', 'Paste'),
(gen_random_uuid(), 'Technology', 'Cut', 'Clipboard'),
(gen_random_uuid(), 'Technology', 'Undo', 'Redo'),
(gen_random_uuid(), 'Technology', 'Save', 'Save As'),
(gen_random_uuid(), 'Technology', 'Print', 'Preview'),
(gen_random_uuid(), 'Technology', 'Search', 'Find'),
(gen_random_uuid(), 'Technology', 'Replace', 'Find and Replace'),
(gen_random_uuid(), 'Technology', 'Bold', 'Italic'),
(gen_random_uuid(), 'Technology', 'Font', 'Typeface'),
(gen_random_uuid(), 'Technology', 'Zoom', 'Magnify'),
(gen_random_uuid(), 'Technology', 'Minimize', 'Maximize'),
(gen_random_uuid(), 'Technology', 'Window', 'Tab'),
(gen_random_uuid(), 'Technology', 'Desktop', 'Wallpaper'),
(gen_random_uuid(), 'Technology', 'Folder', 'Directory'),
(gen_random_uuid(), 'Technology', 'File', 'Document'),
(gen_random_uuid(), 'Technology', 'Icon', 'Shortcut'),
(gen_random_uuid(), 'Technology', 'Menu', 'Toolbar'),
(gen_random_uuid(), 'Technology', 'Button', 'Link'),
(gen_random_uuid(), 'Technology', 'Slider', 'Toggle'),
(gen_random_uuid(), 'Technology', 'Checkbox', 'Radio Button'),
(gen_random_uuid(), 'Technology', 'Dropdown', 'Select'),
(gen_random_uuid(), 'Technology', 'Popup', 'Modal'),
(gen_random_uuid(), 'Technology', 'Banner', 'Advertisement'),
(gen_random_uuid(), 'Technology', 'Sidebar', 'Navigation'),
(gen_random_uuid(), 'Technology', 'Header', 'Footer'),
(gen_random_uuid(), 'Technology', 'Homepage', 'Landing Page'),
(gen_random_uuid(), 'Inventions', 'Electricity', 'Light Bulb'),
(gen_random_uuid(), 'Inventions', 'Telephone', 'Call'),
(gen_random_uuid(), 'Inventions', 'Television', 'Remote'),
(gen_random_uuid(), 'Inventions', 'Radio', 'Station'),
(gen_random_uuid(), 'Inventions', 'Camera', 'Photograph'),
(gen_random_uuid(), 'Inventions', 'Microwave', 'Popcorn'),
(gen_random_uuid(), 'Inventions', 'Refrigerator', 'Freezer'),
(gen_random_uuid(), 'Inventions', 'Air Conditioner', 'Thermostat'),
(gen_random_uuid(), 'Inventions', 'Vacuum', 'Carpet'),
(gen_random_uuid(), 'Inventions', 'Washing Machine', 'Laundry'),
(gen_random_uuid(), 'Inventions', 'Dishwasher', 'Detergent'),
(gen_random_uuid(), 'Inventions', 'Toaster', 'Bread'),
(gen_random_uuid(), 'Inventions', 'Blender', 'Smoothie'),
(gen_random_uuid(), 'Inventions', 'Coffee Maker', 'Espresso'),
(gen_random_uuid(), 'Inventions', 'Elevator', 'Lift'),
(gen_random_uuid(), 'Inventions', 'Escalator', 'Stairs'),
(gen_random_uuid(), 'Inventions', 'Airplane', 'Runway'),
(gen_random_uuid(), 'Inventions', 'Automobile', 'Engine'),
(gen_random_uuid(), 'Inventions', 'Bicycle', 'Pedal'),
(gen_random_uuid(), 'Inventions', 'Train', 'Railroad'),
(gen_random_uuid(), 'Inventions', 'Submarine', 'Periscope'),
(gen_random_uuid(), 'Inventions', 'Rocket', 'Launch'),
(gen_random_uuid(), 'Inventions', 'Telescope', 'Observatory'),
(gen_random_uuid(), 'Inventions', 'Microscope', 'Bacteria'),
(gen_random_uuid(), 'Inventions', 'Compass', 'Direction'),
(gen_random_uuid(), 'Inventions', 'Calculator', 'Equation'),
(gen_random_uuid(), 'Inventions', 'Clock', 'Time'),
(gen_random_uuid(), 'Inventions', 'Watch', 'Wristband'),
(gen_random_uuid(), 'Inventions', 'Thermometer', 'Temperature'),
(gen_random_uuid(), 'Inventions', 'Barometer', 'Pressure'),
(gen_random_uuid(), 'Inventions', 'Stethoscope', 'Heartbeat'),
(gen_random_uuid(), 'Inventions', 'X-Ray', 'Skeleton'),
(gen_random_uuid(), 'Inventions', 'Pacemaker', 'Heart'),
(gen_random_uuid(), 'Inventions', 'Contact Lens', 'Vision'),
(gen_random_uuid(), 'Inventions', 'Hearing Aid', 'Deaf'),
(gen_random_uuid(), 'Inventions', 'Wheelchair', 'Mobility'),
(gen_random_uuid(), 'Inventions', 'Prosthetic', 'Limb'),
(gen_random_uuid(), 'Inventions', 'Braille', 'Blind'),
(gen_random_uuid(), 'Inventions', 'Pencil', 'Eraser'),
(gen_random_uuid(), 'Inventions', 'Pen', 'Ink'),
(gen_random_uuid(), 'Inventions', 'Paper', 'Pulp'),
(gen_random_uuid(), 'Inventions', 'Printing Press', 'Gutenberg'),
(gen_random_uuid(), 'Inventions', 'Typewriter', 'Keys'),
(gen_random_uuid(), 'Inventions', 'Photocopy', 'Xerox'),
(gen_random_uuid(), 'Inventions', 'Fax', 'Transmission'),
(gen_random_uuid(), 'Inventions', 'Zipper', 'Jacket'),
(gen_random_uuid(), 'Inventions', 'Velcro', 'Hook'),
(gen_random_uuid(), 'Inventions', 'Post-it Note', 'Sticky'),
(gen_random_uuid(), 'Inventions', 'Scotch Tape', 'Adhesive'),
(gen_random_uuid(), 'Inventions', 'Band-Aid', 'Bandage'),
(gen_random_uuid(), 'Inventions', 'Safety Pin', 'Diaper'),
(gen_random_uuid(), 'Inventions', 'Paperclip', 'Stapler'),
(gen_random_uuid(), 'Inventions', 'Rubber Band', 'Elastic'),
(gen_random_uuid(), 'Inventions', 'Match', 'Lighter'),
(gen_random_uuid(), 'Inventions', 'Candle', 'Wick'),
(gen_random_uuid(), 'Inventions', 'Battery', 'Alkaline'),
(gen_random_uuid(), 'Inventions', 'Solar Panel', 'Renewable'),
(gen_random_uuid(), 'Inventions', 'Wind Turbine', 'Generator'),
(gen_random_uuid(), 'Inventions', 'Dam', 'Hydroelectric'),
(gen_random_uuid(), 'Inventions', 'Nuclear Reactor', 'Uranium'),
(gen_random_uuid(), 'Inventions', 'Dynamite', 'Explosion'),
(gen_random_uuid(), 'Inventions', 'Gunpowder', 'Fireworks'),
(gen_random_uuid(), 'Inventions', 'Wheel', 'Axle'),
(gen_random_uuid(), 'Inventions', 'Lever', 'Fulcrum'),
(gen_random_uuid(), 'Inventions', 'Pulley', 'Rope'),
(gen_random_uuid(), 'Inventions', 'Screw', 'Thread'),
(gen_random_uuid(), 'Inventions', 'Nail', 'Hammer'),
(gen_random_uuid(), 'Inventions', 'Saw', 'Blade'),
(gen_random_uuid(), 'Inventions', 'Drill', 'Bit'),
(gen_random_uuid(), 'Inventions', 'Wrench', 'Bolt'),
(gen_random_uuid(), 'Inventions', 'Pliers', 'Grip'),
(gen_random_uuid(), 'Inventions', 'Screwdriver', 'Phillips'),
(gen_random_uuid(), 'Inventions', 'Measuring Tape', 'Ruler'),
(gen_random_uuid(), 'Inventions', 'Level', 'Bubble'),
(gen_random_uuid(), 'Inventions', 'Flashlight', 'Beam'),
(gen_random_uuid(), 'Inventions', 'Laser', 'Pointer'),
(gen_random_uuid(), 'Inventions', 'Magnet', 'Attract'),
(gen_random_uuid(), 'Inventions', 'Barcode', 'Scanner'),
(gen_random_uuid(), 'Inventions', 'QR Code', 'Smartphone'),
(gen_random_uuid(), 'Inventions', 'ATM', 'Cash'),
(gen_random_uuid(), 'Inventions', 'Credit Card', 'Swipe'),
(gen_random_uuid(), 'Inventions', 'Vending Machine', 'Snack'),
(gen_random_uuid(), 'Inventions', 'Turnstile', 'Subway'),
(gen_random_uuid(), 'Inventions', 'Revolving Door', 'Entrance'),
(gen_random_uuid(), 'Inventions', 'Automatic Door', 'Sensor'),
(gen_random_uuid(), 'Inventions', 'Traffic Light', 'Intersection'),
(gen_random_uuid(), 'Inventions', 'Parking Meter', 'Coin'),
(gen_random_uuid(), 'Inventions', 'Fire Alarm', 'Smoke'),
(gen_random_uuid(), 'Inventions', 'Sprinkler', 'Fire'),
(gen_random_uuid(), 'Inventions', 'Fire Extinguisher', 'Foam'),

-- ANIMALS & NATURE (300 pairs)
(gen_random_uuid(), 'Animals', 'Dog', 'Bark'),
(gen_random_uuid(), 'Animals', 'Cat', 'Meow'),
(gen_random_uuid(), 'Animals', 'Bird', 'Feather'),
(gen_random_uuid(), 'Animals', 'Fish', 'Scales'),
(gen_random_uuid(), 'Animals', 'Horse', 'Stable'),
(gen_random_uuid(), 'Animals', 'Cow', 'Udder'),
(gen_random_uuid(), 'Animals', 'Pig', 'Snout'),
(gen_random_uuid(), 'Animals', 'Sheep', 'Wool'),
(gen_random_uuid(), 'Animals', 'Goat', 'Horns'),
(gen_random_uuid(), 'Animals', 'Chicken', 'Coop'),
(gen_random_uuid(), 'Animals', 'Duck', 'Waddle'),
(gen_random_uuid(), 'Animals', 'Turkey', 'Gobble'),
(gen_random_uuid(), 'Animals', 'Rabbit', 'Burrow'),
(gen_random_uuid(), 'Animals', 'Mouse', 'Cheese'),
(gen_random_uuid(), 'Animals', 'Rat', 'Sewer'),
(gen_random_uuid(), 'Animals', 'Hamster', 'Wheel'),
(gen_random_uuid(), 'Animals', 'Guinea Pig', 'Squeak'),
(gen_random_uuid(), 'Animals', 'Ferret', 'Weasel'),
(gen_random_uuid(), 'Animals', 'Squirrel', 'Acorn'),
(gen_random_uuid(), 'Animals', 'Chipmunk', 'Cheeks'),
(gen_random_uuid(), 'Animals', 'Beaver', 'Dam'),
(gen_random_uuid(), 'Animals', 'Otter', 'River'),
(gen_random_uuid(), 'Animals', 'Raccoon', 'Trash'),
(gen_random_uuid(), 'Animals', 'Skunk', 'Spray'),
(gen_random_uuid(), 'Animals', 'Porcupine', 'Quills'),
(gen_random_uuid(), 'Animals', 'Deer', 'Antlers'),
(gen_random_uuid(), 'Animals', 'Moose', 'Elk'),
(gen_random_uuid(), 'Animals', 'Caribou', 'Reindeer'),
(gen_random_uuid(), 'Animals', 'Bear', 'Hibernate'),
(gen_random_uuid(), 'Animals', 'Wolf', 'Pack'),
(gen_random_uuid(), 'Animals', 'Fox', 'Den'),
(gen_random_uuid(), 'Animals', 'Coyote', 'Howl'),
(gen_random_uuid(), 'Animals', 'Lion', 'Mane'),
(gen_random_uuid(), 'Animals', 'Tiger', 'Stripes'),
(gen_random_uuid(), 'Animals', 'Leopard', 'Spots'),
(gen_random_uuid(), 'Animals', 'Cheetah', 'Speed'),
(gen_random_uuid(), 'Animals', 'Jaguar', 'Jungle'),
(gen_random_uuid(), 'Animals', 'Panther', 'Black Cat'),
(gen_random_uuid(), 'Animals', 'Elephant', 'Trunk'),
(gen_random_uuid(), 'Animals', 'Rhino', 'Horn'),
(gen_random_uuid(), 'Animals', 'Hippo', 'River'),
(gen_random_uuid(), 'Animals', 'Giraffe', 'Neck'),
(gen_random_uuid(), 'Animals', 'Zebra', 'Stripes'),
(gen_random_uuid(), 'Animals', 'Antelope', 'Gazelle'),
(gen_random_uuid(), 'Animals', 'Buffalo', 'Bison'),
(gen_random_uuid(), 'Animals', 'Wildebeest', 'Migration'),
(gen_random_uuid(), 'Animals', 'Gorilla', 'Silverback'),
(gen_random_uuid(), 'Animals', 'Chimpanzee', 'Primate'),
(gen_random_uuid(), 'Animals', 'Orangutan', 'Ape'),
(gen_random_uuid(), 'Animals', 'Monkey', 'Banana'),
(gen_random_uuid(), 'Animals', 'Baboon', 'Troop'),
(gen_random_uuid(), 'Animals', 'Lemur', 'Madagascar'),
(gen_random_uuid(), 'Animals', 'Sloth', 'Slow'),
(gen_random_uuid(), 'Animals', 'Armadillo', 'Shell'),
(gen_random_uuid(), 'Animals', 'Anteater', 'Tongue'),
(gen_random_uuid(), 'Animals', 'Platypus', 'Bill'),
(gen_random_uuid(), 'Animals', 'Kangaroo', 'Pouch'),
(gen_random_uuid(), 'Animals', 'Koala', 'Eucalyptus'),
(gen_random_uuid(), 'Animals', 'Wombat', 'Burrow'),
(gen_random_uuid(), 'Animals', 'Tasmanian Devil', 'Tasmania'),
(gen_random_uuid(), 'Animals', 'Penguin', 'Antarctica'),
(gen_random_uuid(), 'Animals', 'Polar Bear', 'Arctic'),
(gen_random_uuid(), 'Animals', 'Seal', 'Flipper'),
(gen_random_uuid(), 'Animals', 'Walrus', 'Tusk'),
(gen_random_uuid(), 'Animals', 'Dolphin', 'Pod'),
(gen_random_uuid(), 'Animals', 'Whale', 'Blowhole'),
(gen_random_uuid(), 'Animals', 'Shark', 'Fin'),
(gen_random_uuid(), 'Animals', 'Octopus', 'Tentacles'),
(gen_random_uuid(), 'Animals', 'Squid', 'Ink'),
(gen_random_uuid(), 'Animals', 'Jellyfish', 'Sting'),
(gen_random_uuid(), 'Animals', 'Starfish', 'Reef'),
(gen_random_uuid(), 'Animals', 'Crab', 'Claws'),
(gen_random_uuid(), 'Animals', 'Lobster', 'Shell'),
(gen_random_uuid(), 'Animals', 'Shrimp', 'Prawn'),
(gen_random_uuid(), 'Animals', 'Oyster', 'Pearl'),
(gen_random_uuid(), 'Animals', 'Clam', 'Chowder'),
(gen_random_uuid(), 'Animals', 'Snail', 'Slime'),
(gen_random_uuid(), 'Animals', 'Slug', 'Garden'),
(gen_random_uuid(), 'Animals', 'Worm', 'Soil'),
(gen_random_uuid(), 'Animals', 'Butterfly', 'Cocoon'),
(gen_random_uuid(), 'Animals', 'Moth', 'Lamp'),
(gen_random_uuid(), 'Animals', 'Caterpillar', 'Chrysalis'),
(gen_random_uuid(), 'Animals', 'Bee', 'Hive'),
(gen_random_uuid(), 'Animals', 'Wasp', 'Nest'),
(gen_random_uuid(), 'Animals', 'Hornet', 'Sting'),
(gen_random_uuid(), 'Animals', 'Ant', 'Colony'),
(gen_random_uuid(), 'Animals', 'Termite', 'Mound'),
(gen_random_uuid(), 'Animals', 'Beetle', 'Larvae'),
(gen_random_uuid(), 'Animals', 'Ladybug', 'Spots'),
(gen_random_uuid(), 'Animals', 'Firefly', 'Glow'),
(gen_random_uuid(), 'Animals', 'Dragonfly', 'Wings'),
(gen_random_uuid(), 'Animals', 'Grasshopper', 'Jump'),
(gen_random_uuid(), 'Animals', 'Cricket', 'Chirp'),
(gen_random_uuid(), 'Animals', 'Mosquito', 'Bite'),
(gen_random_uuid(), 'Animals', 'Fly', 'Buzz'),
(gen_random_uuid(), 'Animals', 'Flea', 'Itch'),
(gen_random_uuid(), 'Animals', 'Tick', 'Blood'),
(gen_random_uuid(), 'Animals', 'Spider', 'Web'),
(gen_random_uuid(), 'Animals', 'Scorpion', 'Tail'),
(gen_random_uuid(), 'Animals', 'Tarantula', 'Hairy'),
(gen_random_uuid(), 'Animals', 'Centipede', 'Legs'),
(gen_random_uuid(), 'Animals', 'Millipede', 'Segments'),
(gen_random_uuid(), 'Animals', 'Snake', 'Venom'),
(gen_random_uuid(), 'Animals', 'Python', 'Constrict'),
(gen_random_uuid(), 'Animals', 'Cobra', 'Hood'),
(gen_random_uuid(), 'Animals', 'Rattlesnake', 'Rattle'),
(gen_random_uuid(), 'Animals', 'Lizard', 'Tail'),
(gen_random_uuid(), 'Animals', 'Gecko', 'Wall'),
(gen_random_uuid(), 'Animals', 'Iguana', 'Dewlap'),
(gen_random_uuid(), 'Animals', 'Chameleon', 'Camouflage'),
(gen_random_uuid(), 'Animals', 'Alligator', 'Swamp'),
(gen_random_uuid(), 'Animals', 'Crocodile', 'Nile'),
(gen_random_uuid(), 'Animals', 'Turtle', 'Shell'),
(gen_random_uuid(), 'Animals', 'Tortoise', 'Slow'),
(gen_random_uuid(), 'Animals', 'Frog', 'Tadpole'),
(gen_random_uuid(), 'Animals', 'Toad', 'Warts'),
(gen_random_uuid(), 'Animals', 'Salamander', 'Newt'),
(gen_random_uuid(), 'Animals', 'Eagle', 'Talons'),
(gen_random_uuid(), 'Animals', 'Hawk', 'Prey'),
(gen_random_uuid(), 'Animals', 'Falcon', 'Dive'),
(gen_random_uuid(), 'Animals', 'Owl', 'Hoot'),
(gen_random_uuid(), 'Animals', 'Vulture', 'Carrion'),
(gen_random_uuid(), 'Animals', 'Raven', 'Crow'),
(gen_random_uuid(), 'Animals', 'Parrot', 'Talk'),
(gen_random_uuid(), 'Animals', 'Macaw', 'Colorful'),
(gen_random_uuid(), 'Animals', 'Toucan', 'Beak'),
(gen_random_uuid(), 'Animals', 'Flamingo', 'Pink'),
(gen_random_uuid(), 'Animals', 'Peacock', 'Feathers'),
(gen_random_uuid(), 'Animals', 'Swan', 'Grace'),
(gen_random_uuid(), 'Animals', 'Goose', 'Honk'),
(gen_random_uuid(), 'Animals', 'Pelican', 'Pouch'),
(gen_random_uuid(), 'Animals', 'Seagull', 'Beach'),
(gen_random_uuid(), 'Animals', 'Albatross', 'Wingspan'),
(gen_random_uuid(), 'Animals', 'Hummingbird', 'Nectar'),
(gen_random_uuid(), 'Animals', 'Woodpecker', 'Peck'),
(gen_random_uuid(), 'Animals', 'Robin', 'Worm'),
(gen_random_uuid(), 'Animals', 'Blue Jay', 'Loud'),
(gen_random_uuid(), 'Animals', 'Cardinal', 'Red'),
(gen_random_uuid(), 'Animals', 'Pigeon', 'Coo'),
(gen_random_uuid(), 'Animals', 'Dove', 'Peace'),
(gen_random_uuid(), 'Animals', 'Sparrow', 'Common'),
(gen_random_uuid(), 'Animals', 'Ostrich', 'Flightless'),
(gen_random_uuid(), 'Animals', 'Emu', 'Australia'),
(gen_random_uuid(), 'Animals', 'Kiwi', 'New Zealand'),
(gen_random_uuid(), 'Animals', 'Panda', 'Bamboo'),
(gen_random_uuid(), 'Animals', 'Llama', 'Spit'),
(gen_random_uuid(), 'Animals', 'Alpaca', 'Wool'),
(gen_random_uuid(), 'Animals', 'Camel', 'Hump'),
(gen_random_uuid(), 'Animals', 'Donkey', 'Bray'),
(gen_random_uuid(), 'Animals', 'Mule', 'Stubborn'),
(gen_random_uuid(), 'Animals', 'Hedgehog', 'Spikes'),
(gen_random_uuid(), 'Animals', 'Badger', 'Burrow'),
(gen_random_uuid(), 'Animals', 'Mole', 'Underground'),
(gen_random_uuid(), 'Animals', 'Bat', 'Echolocation'),
(gen_random_uuid(), 'Animals', 'Hyena', 'Laugh'),
(gen_random_uuid(), 'Animals', 'Meerkat', 'Lookout'),
(gen_random_uuid(), 'Animals', 'Mongoose', 'Snake'),
(gen_random_uuid(), 'Animals', 'Warthog', 'Tusks'),
(gen_random_uuid(), 'Animals', 'Yak', 'Tibet'),
(gen_random_uuid(), 'Animals', 'Bison', 'Buffalo'),
(gen_random_uuid(), 'Nature', 'Tree', 'Branch'),
(gen_random_uuid(), 'Nature', 'Flower', 'Petal'),
(gen_random_uuid(), 'Nature', 'Grass', 'Lawn'),
(gen_random_uuid(), 'Nature', 'Rose', 'Thorn'),
(gen_random_uuid(), 'Nature', 'Sunflower', 'Seeds'),
(gen_random_uuid(), 'Nature', 'Tulip', 'Bulb'),
(gen_random_uuid(), 'Nature', 'Daisy', 'White'),
(gen_random_uuid(), 'Nature', 'Lily', 'Pond'),
(gen_random_uuid(), 'Nature', 'Orchid', 'Exotic'),
(gen_random_uuid(), 'Nature', 'Cactus', 'Desert'),
(gen_random_uuid(), 'Nature', 'Fern', 'Frond'),
(gen_random_uuid(), 'Nature', 'Moss', 'Rock'),
(gen_random_uuid(), 'Nature', 'Mushroom', 'Fungi'),
(gen_random_uuid(), 'Nature', 'Seaweed', 'Ocean'),
(gen_random_uuid(), 'Nature', 'Coral', 'Reef'),
(gen_random_uuid(), 'Nature', 'Pine Tree', 'Cone'),
(gen_random_uuid(), 'Nature', 'Oak Tree', 'Acorn'),
(gen_random_uuid(), 'Nature', 'Maple Tree', 'Syrup'),
(gen_random_uuid(), 'Nature', 'Willow Tree', 'Weeping'),
(gen_random_uuid(), 'Nature', 'Palm Tree', 'Tropical'),
(gen_random_uuid(), 'Nature', 'Bamboo', 'Panda'),
(gen_random_uuid(), 'Nature', 'Vine', 'Climb'),
(gen_random_uuid(), 'Nature', 'Ivy', 'Wall'),
(gen_random_uuid(), 'Nature', 'Weed', 'Dandelion'),
(gen_random_uuid(), 'Nature', 'Leaf', 'Autumn'),
(gen_random_uuid(), 'Nature', 'Root', 'Underground'),
(gen_random_uuid(), 'Nature', 'Seed', 'Germinate'),
(gen_random_uuid(), 'Nature', 'Fruit', 'Ripen'),
(gen_random_uuid(), 'Nature', 'Berry', 'Bush'),
(gen_random_uuid(), 'Nature', 'Nut', 'Shell'),
(gen_random_uuid(), 'Nature', 'Grain', 'Wheat'),
(gen_random_uuid(), 'Nature', 'Vegetable', 'Garden'),
(gen_random_uuid(), 'Nature', 'Mountain', 'Peak'),
(gen_random_uuid(), 'Nature', 'Valley', 'Canyon'),
(gen_random_uuid(), 'Nature', 'River', 'Stream'),
(gen_random_uuid(), 'Nature', 'Lake', 'Shore'),
(gen_random_uuid(), 'Nature', 'Ocean', 'Wave'),
(gen_random_uuid(), 'Nature', 'Sea', 'Coast'),
(gen_random_uuid(), 'Nature', 'Beach', 'Sand'),
(gen_random_uuid(), 'Nature', 'Island', 'Lagoon'),
(gen_random_uuid(), 'Nature', 'Forest', 'Woods'),
(gen_random_uuid(), 'Nature', 'Jungle', 'Rainforest'),
(gen_random_uuid(), 'Nature', 'Desert', 'Dunes'),
(gen_random_uuid(), 'Nature', 'Tundra', 'Arctic'),
(gen_random_uuid(), 'Nature', 'Prairie', 'Plains'),
(gen_random_uuid(), 'Nature', 'Swamp', 'Marsh'),
(gen_random_uuid(), 'Nature', 'Wetland', 'Bog'),
(gen_random_uuid(), 'Nature', 'Cliff', 'Edge'),
(gen_random_uuid(), 'Nature', 'Cave', 'Cavern'),
(gen_random_uuid(), 'Nature', 'Volcano', 'Lava'),
(gen_random_uuid(), 'Nature', 'Geyser', 'Eruption'),
(gen_random_uuid(), 'Nature', 'Glacier', 'Ice'),
(gen_random_uuid(), 'Nature', 'Iceberg', 'Titanic'),
(gen_random_uuid(), 'Nature', 'Waterfall', 'Cascade'),
(gen_random_uuid(), 'Nature', 'Rapids', 'White Water'),
(gen_random_uuid(), 'Weather', 'Rain', 'Umbrella'),
(gen_random_uuid(), 'Weather', 'Snow', 'Snowflake'),
(gen_random_uuid(), 'Weather', 'Hail', 'Ice'),
(gen_random_uuid(), 'Weather', 'Sleet', 'Freezing'),
(gen_random_uuid(), 'Weather', 'Thunder', 'Lightning'),
(gen_random_uuid(), 'Weather', 'Storm', 'Hurricane'),
(gen_random_uuid(), 'Weather', 'Tornado', 'Twister'),
(gen_random_uuid(), 'Weather', 'Wind', 'Breeze'),
(gen_random_uuid(), 'Weather', 'Cloud', 'Sky'),
(gen_random_uuid(), 'Weather', 'Fog', 'Mist'),
(gen_random_uuid(), 'Weather', 'Sunshine', 'Bright'),
(gen_random_uuid(), 'Weather', 'Rainbow', 'Prism'),
(gen_random_uuid(), 'Weather', 'Frost', 'Morning'),
(gen_random_uuid(), 'Weather', 'Dew', 'Grass'),
(gen_random_uuid(), 'Weather', 'Drought', 'Dry'),
(gen_random_uuid(), 'Weather', 'Flood', 'Deluge'),
(gen_random_uuid(), 'Weather', 'Blizzard', 'Whiteout'),
(gen_random_uuid(), 'Weather', 'Heat Wave', 'Temperature'),
-- FOOD & DRINK (400 pairs)
(gen_random_uuid(), 'Food', 'Pizza', 'Pepperoni'),
(gen_random_uuid(), 'Food', 'Burger', 'Bun'),
(gen_random_uuid(), 'Food', 'Hot Dog', 'Mustard'),
(gen_random_uuid(), 'Food', 'Sandwich', 'Bread'),
(gen_random_uuid(), 'Food', 'Taco', 'Salsa'),
(gen_random_uuid(), 'Food', 'Burrito', 'Tortilla'),
(gen_random_uuid(), 'Food', 'Sushi', 'Wasabi'),
(gen_random_uuid(), 'Food', 'Pasta', 'Marinara'),
(gen_random_uuid(), 'Food', 'Noodles', 'Chopsticks'),
(gen_random_uuid(), 'Food', 'Rice', 'Grain'),
(gen_random_uuid(), 'Food', 'Bread', 'Dough'),
(gen_random_uuid(), 'Food', 'Toast', 'Butter'),
(gen_random_uuid(), 'Food', 'Bagel', 'Cream Cheese'),
(gen_random_uuid(), 'Food', 'Croissant', 'Flaky'),
(gen_random_uuid(), 'Food', 'Muffin', 'Blueberry'),
(gen_random_uuid(), 'Food', 'Donut', 'Glaze'),
(gen_random_uuid(), 'Food', 'Pancake', 'Syrup'),
(gen_random_uuid(), 'Food', 'Waffle', 'Grid'),
(gen_random_uuid(), 'Food', 'Cereal', 'Milk'),
(gen_random_uuid(), 'Food', 'Oatmeal', 'Porridge'),
(gen_random_uuid(), 'Food', 'Eggs', 'Scrambled'),
(gen_random_uuid(), 'Food', 'Bacon', 'Crispy'),
(gen_random_uuid(), 'Food', 'Sausage', 'Link'),
(gen_random_uuid(), 'Food', 'Ham', 'Honey'),
(gen_random_uuid(), 'Food', 'Steak', 'Ribeye'),
(gen_random_uuid(), 'Food', 'Chicken', 'Drumstick'),
(gen_random_uuid(), 'Food', 'Turkey', 'Thanksgiving'),
(gen_random_uuid(), 'Food', 'Pork', 'Chop'),
(gen_random_uuid(), 'Food', 'Lamb', 'Mint'),
(gen_random_uuid(), 'Food', 'Beef', 'Cow'),
(gen_random_uuid(), 'Food', 'Salmon', 'Pink'),
(gen_random_uuid(), 'Food', 'Tuna', 'Can'),
(gen_random_uuid(), 'Food', 'Shrimp', 'Cocktail'),
(gen_random_uuid(), 'Food', 'Lobster', 'Butter'),
(gen_random_uuid(), 'Food', 'Crab', 'Cake'),
(gen_random_uuid(), 'Food', 'Oyster', 'Raw'),
(gen_random_uuid(), 'Food', 'Clam', 'Chowder'),
(gen_random_uuid(), 'Food', 'Cheese', 'Cheddar'),
(gen_random_uuid(), 'Food', 'Milk', 'Dairy'),
(gen_random_uuid(), 'Food', 'Yogurt', 'Culture'),
(gen_random_uuid(), 'Food', 'Butter', 'Spread'),
(gen_random_uuid(), 'Food', 'Cream', 'Whipped'),
(gen_random_uuid(), 'Food', 'Ice Cream', 'Scoop'),
(gen_random_uuid(), 'Food', 'Gelato', 'Italian'),
(gen_random_uuid(), 'Food', 'Sorbet', 'Sherbet'),
(gen_random_uuid(), 'Food', 'Popsicle', 'Frozen'),
(gen_random_uuid(), 'Food', 'Cake', 'Frosting'),
(gen_random_uuid(), 'Food', 'Pie', 'Crust'),
(gen_random_uuid(), 'Food', 'Cookie', 'Chocolate Chip'),
(gen_random_uuid(), 'Food', 'Brownie', 'Fudge'),
(gen_random_uuid(), 'Food', 'Candy', 'Sweet'),
(gen_random_uuid(), 'Food', 'Chocolate', 'Cocoa'),
(gen_random_uuid(), 'Food', 'Caramel', 'Sticky'),
(gen_random_uuid(), 'Food', 'Marshmallow', 'Campfire'),
(gen_random_uuid(), 'Food', 'Jello', 'Jiggly'),
(gen_random_uuid(), 'Food', 'Pudding', 'Custard'),
(gen_random_uuid(), 'Food', 'Cheesecake', 'Graham Cracker'),
(gen_random_uuid(), 'Food', 'Cupcake', 'Sprinkles'),
(gen_random_uuid(), 'Food', 'Apple', 'Core'),
(gen_random_uuid(), 'Food', 'Orange', 'Peel'),
(gen_random_uuid(), 'Food', 'Banana', 'Yellow'),
(gen_random_uuid(), 'Food', 'Grape', 'Vine'),
(gen_random_uuid(), 'Food', 'Strawberry', 'Seeds'),
(gen_random_uuid(), 'Food', 'Blueberry', 'Muffin'),
(gen_random_uuid(), 'Food', 'Raspberry', 'Tart'),
(gen_random_uuid(), 'Food', 'Blackberry', 'Bramble'),
(gen_random_uuid(), 'Food', 'Watermelon', 'Rind'),
(gen_random_uuid(), 'Food', 'Cantaloupe', 'Melon'),
(gen_random_uuid(), 'Food', 'Honeydew', 'Green'),
(gen_random_uuid(), 'Food', 'Pineapple', 'Spiky'),
(gen_random_uuid(), 'Food', 'Mango', 'Tropical'),
(gen_random_uuid(), 'Food', 'Papaya', 'Seeds'),
(gen_random_uuid(), 'Food', 'Kiwi', 'Fuzzy'),
(gen_random_uuid(), 'Food', 'Peach', 'Pit'),
(gen_random_uuid(), 'Food', 'Plum', 'Stone'),
(gen_random_uuid(), 'Food', 'Cherry', 'Stem'),
(gen_random_uuid(), 'Food', 'Pear', 'Shape'),
(gen_random_uuid(), 'Food', 'Lemon', 'Sour'),
(gen_random_uuid(), 'Food', 'Lime', 'Citrus'),
(gen_random_uuid(), 'Food', 'Grapefruit', 'Bitter'),
(gen_random_uuid(), 'Food', 'Coconut', 'Shell'),
(gen_random_uuid(), 'Food', 'Avocado', 'Guacamole'),
(gen_random_uuid(), 'Food', 'Tomato', 'Ketchup'),
(gen_random_uuid(), 'Food', 'Potato', 'Fries'),
(gen_random_uuid(), 'Food', 'Sweet Potato', 'Yam'),
(gen_random_uuid(), 'Food', 'Carrot', 'Orange'),
(gen_random_uuid(), 'Food', 'Broccoli', 'Florets'),
(gen_random_uuid(), 'Food', 'Cauliflower', 'White'),
(gen_random_uuid(), 'Food', 'Lettuce', 'Salad'),
(gen_random_uuid(), 'Food', 'Spinach', 'Popeye'),
(gen_random_uuid(), 'Food', 'Kale', 'Superfood'),
(gen_random_uuid(), 'Food', 'Cabbage', 'Cole Slaw'),
(gen_random_uuid(), 'Food', 'Cucumber', 'Pickle'),
(gen_random_uuid(), 'Food', 'Zucchini', 'Squash'),
(gen_random_uuid(), 'Food', 'Pumpkin', 'Halloween'),
(gen_random_uuid(), 'Food', 'Corn', 'Cob'),
(gen_random_uuid(), 'Food', 'Peas', 'Pod'),
(gen_random_uuid(), 'Food', 'Green Beans', 'String'),
(gen_random_uuid(), 'Food', 'Asparagus', 'Spear'),
(gen_random_uuid(), 'Food', 'Celery', 'Stalk'),
(gen_random_uuid(), 'Food', 'Onion', 'Layers'),
(gen_random_uuid(), 'Food', 'Garlic', 'Clove'),
(gen_random_uuid(), 'Food', 'Pepper', 'Bell'),
(gen_random_uuid(), 'Food', 'Chili', 'Spicy'),
(gen_random_uuid(), 'Food', 'Mushroom', 'Button'),
(gen_random_uuid(), 'Food', 'Eggplant', 'Purple'),
(gen_random_uuid(), 'Food', 'Beet', 'Red'),
(gen_random_uuid(), 'Food', 'Radish', 'Root'),
(gen_random_uuid(), 'Food', 'Turnip', 'Greens'),
(gen_random_uuid(), 'Drinks', 'Water', 'Hydration'),
(gen_random_uuid(), 'Drinks', 'Coffee', 'Caffeine'),
(gen_random_uuid(), 'Drinks', 'Tea', 'Steep'),
(gen_random_uuid(), 'Drinks', 'Juice', 'Fresh'),
(gen_random_uuid(), 'Drinks', 'Soda', 'Fizz'),
(gen_random_uuid(), 'Drinks', 'Cola', 'Pepsi'),
(gen_random_uuid(), 'Drinks', 'Lemonade', 'Pink'),
(gen_random_uuid(), 'Drinks', 'Smoothie', 'Blend'),
(gen_random_uuid(), 'Drinks', 'Milkshake', 'Straw'),
(gen_random_uuid(), 'Drinks', 'Beer', 'Hops'),
(gen_random_uuid(), 'Drinks', 'Wine', 'Grapes'),
(gen_random_uuid(), 'Drinks', 'Champagne', 'Bubbles'),
(gen_random_uuid(), 'Drinks', 'Cocktail', 'Mixed'),
(gen_random_uuid(), 'Drinks', 'Margarita', 'Salt'),
(gen_random_uuid(), 'Drinks', 'Martini', 'Olive'),
(gen_random_uuid(), 'Drinks', 'Mojito', 'Mint'),
(gen_random_uuid(), 'Drinks', 'Whiskey', 'Bourbon'),
(gen_random_uuid(), 'Drinks', 'Vodka', 'Russia'),
(gen_random_uuid(), 'Drinks', 'Rum', 'Pirate'),
(gen_random_uuid(), 'Drinks', 'Tequila', 'Agave'),
(gen_random_uuid(), 'Drinks', 'Gin', 'Tonic'),
(gen_random_uuid(), 'Drinks', 'Sake', 'Japanese'),
(gen_random_uuid(), 'Drinks', 'Hot Chocolate', 'Marshmallow'),
(gen_random_uuid(), 'Drinks', 'Cappuccino', 'Foam'),
(gen_random_uuid(), 'Drinks', 'Latte', 'Espresso'),
(gen_random_uuid(), 'Drinks', 'Espresso', 'Shot'),
(gen_random_uuid(), 'Drinks', 'Frappuccino', 'Starbucks'),
(gen_random_uuid(), 'Drinks', 'Iced Tea', 'Sweet'),
(gen_random_uuid(), 'Drinks', 'Green Tea', 'Matcha'),
(gen_random_uuid(), 'Drinks', 'Apple Juice', 'Cider'),
(gen_random_uuid(), 'Drinks', 'Orange Juice', 'Pulp'),
(gen_random_uuid(), 'Drinks', 'Cranberry Juice', 'Tart'),
(gen_random_uuid(), 'Drinks', 'Grapefruit Juice', 'Bitter'),
(gen_random_uuid(), 'Drinks', 'Pineapple Juice', 'Tropical'),
(gen_random_uuid(), 'Drinks', 'Coconut Water', 'Refreshing'),
(gen_random_uuid(), 'Drinks', 'Sports Drink', 'Gatorade'),
(gen_random_uuid(), 'Drinks', 'Energy Drink', 'Red Bull'),
(gen_random_uuid(), 'Condiments', 'Ketchup', 'Tomato'),
(gen_random_uuid(), 'Condiments', 'Mustard', 'Yellow'),
(gen_random_uuid(), 'Condiments', 'Mayonnaise', 'Egg'),
(gen_random_uuid(), 'Condiments', 'BBQ Sauce', 'Ribs'),
(gen_random_uuid(), 'Condiments', 'Hot Sauce', 'Tabasco'),
(gen_random_uuid(), 'Condiments', 'Soy Sauce', 'Sushi'),
(gen_random_uuid(), 'Condiments', 'Ranch', 'Dressing'),
(gen_random_uuid(), 'Condiments', 'Vinegar', 'Pickle'),
(gen_random_uuid(), 'Condiments', 'Olive Oil', 'Extra Virgin'),
(gen_random_uuid(), 'Condiments', 'Honey', 'Bee'),
(gen_random_uuid(), 'Condiments', 'Jam', 'Jelly'),
(gen_random_uuid(), 'Condiments', 'Peanut Butter', 'Jelly'),
(gen_random_uuid(), 'Condiments', 'Nutella', 'Hazelnut'),
(gen_random_uuid(), 'Condiments', 'Maple Syrup', 'Pancake'),
(gen_random_uuid(), 'Condiments', 'Salsa', 'Chips'),
(gen_random_uuid(), 'Condiments', 'Guacamole', 'Avocado'),
(gen_random_uuid(), 'Condiments', 'Hummus', 'Chickpea'),
(gen_random_uuid(), 'Condiments', 'Salad Dressing', 'Italian'),
(gen_random_uuid(), 'Condiments', 'Gravy', 'Mashed Potatoes'),
(gen_random_uuid(), 'Condiments', 'Relish', 'Hot Dog'),
(gen_random_uuid(), 'Condiments', 'Tartar Sauce', 'Fish'),
(gen_random_uuid(), 'Condiments', 'Cocktail Sauce', 'Shrimp'),
(gen_random_uuid(), 'Condiments', 'Sriracha', 'Rooster'),
(gen_random_uuid(), 'Condiments', 'Teriyaki', 'Glaze'),
(gen_random_uuid(), 'Snacks', 'Chips', 'Potato'),
(gen_random_uuid(), 'Snacks', 'Popcorn', 'Butter'),
(gen_random_uuid(), 'Snacks', 'Pretzels', 'Salt'),
(gen_random_uuid(), 'Snacks', 'Crackers', 'Cheese'),
(gen_random_uuid(), 'Snacks', 'Cookies', 'Oreo'),
(gen_random_uuid(), 'Snacks', 'Candy Bar', 'Wrapper'),
(gen_random_uuid(), 'Snacks', 'Gummy Bears', 'Chewy'),
(gen_random_uuid(), 'Snacks', 'Licorice', 'Red'),
(gen_random_uuid(), 'Snacks', 'Peanuts', 'Shell'),
(gen_random_uuid(), 'Snacks', 'Cashews', 'Roasted'),
(gen_random_uuid(), 'Snacks', 'Almonds', 'Crunchy'),
(gen_random_uuid(), 'Snacks', 'Trail Mix', 'Hiking'),
(gen_random_uuid(), 'Snacks', 'Granola Bar', 'Oats'),
(gen_random_uuid(), 'Snacks', 'Beef Jerky', 'Dried'),
(gen_random_uuid(), 'Snacks', 'String Cheese', 'Peel'),
(gen_random_uuid(), 'Snacks', 'Fruit Roll-Up', 'Sticky'),
(gen_random_uuid(), 'Snacks', 'Rice Cake', 'Puffed'),
(gen_random_uuid(), 'Snacks', 'Tortilla Chips', 'Nacho'),
(gen_random_uuid(), 'Snacks', 'Cheese Puffs', 'Orange'),
(gen_random_uuid(), 'Snacks', 'Goldfish', 'Crackers'),

-- SPORTS & ACTIVITIES (300 pairs)
(gen_random_uuid(), 'Sports', 'Football', 'Touchdown'),
(gen_random_uuid(), 'Sports', 'Basketball', 'Hoop'),
(gen_random_uuid(), 'Sports', 'Baseball', 'Diamond'),
(gen_random_uuid(), 'Sports', 'Soccer', 'Goal'),
(gen_random_uuid(), 'Sports', 'Tennis', 'Racket'),
(gen_random_uuid(), 'Sports', 'Golf', 'Hole'),
(gen_random_uuid(), 'Sports', 'Hockey', 'Puck'),
(gen_random_uuid(), 'Sports', 'Volleyball', 'Spike'),
(gen_random_uuid(), 'Sports', 'Swimming', 'Pool'),
(gen_random_uuid(), 'Sports', 'Running', 'Marathon'),
(gen_random_uuid(), 'Sports', 'Cycling', 'Pedal'),
(gen_random_uuid(), 'Sports', 'Boxing', 'Ring'),
(gen_random_uuid(), 'Sports', 'Wrestling', 'Mat'),
(gen_random_uuid(), 'Sports', 'Karate', 'Belt'),
(gen_random_uuid(), 'Sports', 'Judo', 'Throw'),
(gen_random_uuid(), 'Sports', 'Taekwondo', 'Kick'),
(gen_random_uuid(), 'Sports', 'Gymnastics', 'Vault'),
(gen_random_uuid(), 'Sports', 'Track', 'Relay'),
(gen_random_uuid(), 'Sports', 'CrossCountry', 'Distance'),
(gen_random_uuid(), 'Sports', 'Sprinting', '100m'),
(gen_random_uuid(), 'Sports', 'Hurdles', 'Jump'),
(gen_random_uuid(), 'Sports', 'Long Jump', 'Sand'),
(gen_random_uuid(), 'Sports', 'High Jump', 'Bar'),
(gen_random_uuid(), 'Sports', 'Pole Vault', 'Fiberglass'),
(gen_random_uuid(), 'Sports', 'Shot Put', 'Throw'),
(gen_random_uuid(), 'Sports', 'Discus', 'Spin'),
(gen_random_uuid(), 'Sports', 'Javelin', 'Spear'),
(gen_random_uuid(), 'Sports', 'Skiing', 'Slope'),
(gen_random_uuid(), 'Sports', 'Snowboarding', 'Halfpipe'),
(gen_random_uuid(), 'Sports', 'Ice Skating', 'Rink'),
(gen_random_uuid(), 'Sports', 'Figure Skating', 'Spin'),
(gen_random_uuid(), 'Sports', 'Surfing', 'Wave'),
(gen_random_uuid(), 'Sports', 'Skateboarding', 'Ollie'),
(gen_random_uuid(), 'Sports', 'BMX', 'Bike'),
(gen_random_uuid(), 'Sports', 'Rock Climbing', 'Boulder'),
(gen_random_uuid(), 'Sports', 'Hiking', 'Trail'),
(gen_random_uuid(), 'Sports', 'Camping', 'Tent'),
(gen_random_uuid(), 'Sports', 'Fishing', 'Rod'),
(gen_random_uuid(), 'Sports', 'Hunting', 'Rifle'),
(gen_random_uuid(), 'Sports', 'Archery', 'Arrow'),
(gen_random_uuid(), 'Sports', 'Bowling', 'Strike'),
(gen_random_uuid(), 'Sports', 'Billiards', 'Cue'),
(gen_random_uuid(), 'Sports', 'Darts', 'Bullseye'),
(gen_random_uuid(), 'Sports', 'Ping Pong', 'Paddle'),
(gen_random_uuid(), 'Sports', 'Badminton', 'Shuttlecock'),
(gen_random_uuid(), 'Sports', 'Squash', 'Wall'),
(gen_random_uuid(), 'Sports', 'Racquetball', 'Court'),
(gen_random_uuid(), 'Sports', 'Lacrosse', 'Stick'),
(gen_random_uuid(), 'Sports', 'Rugby', 'Scrum'),
(gen_random_uuid(), 'Sports', 'Cricket', 'Wicket'),
(gen_random_uuid(), 'Sports', 'Fencing', 'Foil'),
(gen_random_uuid(), 'Sports', 'Rowing', 'Oar'),
(gen_random_uuid(), 'Sports', 'Kayaking', 'Paddle'),
(gen_random_uuid(), 'Sports', 'Canoeing', 'River'),
(gen_random_uuid(), 'Sports', 'Sailing', 'Wind'),
(gen_random_uuid(), 'Sports', 'Windsurfing', 'Board'),
(gen_random_uuid(), 'Sports', 'Kite Surfing', 'Kite'),
(gen_random_uuid(), 'Sports', 'Scuba Diving', 'Tank'),
(gen_random_uuid(), 'Sports', 'Snorkeling', 'Mask'),
(gen_random_uuid(), 'Sports', 'Water Polo', 'Goal'),
(gen_random_uuid(), 'Sports', 'Synchronized Swimming', 'Routine'),
(gen_random_uuid(), 'Sports', 'Diving', 'Springboard'),
(gen_random_uuid(), 'Sports', 'Triathlon', 'Ironman'),
(gen_random_uuid(), 'Sports', 'Decathlon', 'Ten Events'),
(gen_random_uuid(), 'Sports', 'Pentathlon', 'Five Events'),
(gen_random_uuid(), 'Sports', 'Cheerleading', 'Pyramid'),
(gen_random_uuid(), 'Sports', 'Dance', 'Ballet'),
(gen_random_uuid(), 'Sports', 'Yoga', 'Mat'),
(gen_random_uuid(), 'Sports', 'Pilates', 'Core'),
(gen_random_uuid(), 'Sports', 'Zumba', 'Fitness'),
(gen_random_uuid(), 'Sports', 'Aerobics', 'Cardio'),
(gen_random_uuid(), 'Sports', 'Weightlifting', 'Barbell'),
(gen_random_uuid(), 'Sports', 'Powerlifting', 'Squat'),
(gen_random_uuid(), 'Sports', 'Bodybuilding', 'Muscle'),
(gen_random_uuid(), 'Sports', 'CrossFit', 'WOD'),
(gen_random_uuid(), 'Team Sports', 'Pitcher', 'Catcher'),
(gen_random_uuid(), 'Team Sports', 'Quarterback', 'Receiver'),
(gen_random_uuid(), 'Team Sports', 'Point Guard', 'Shooting Guard'),
(gen_random_uuid(), 'Team Sports', 'Goalkeeper', 'Defender'),
(gen_random_uuid(), 'Team Sports', 'Striker', 'Midfielder'),
(gen_random_uuid(), 'Team Sports', 'Center', 'Forward'),
(gen_random_uuid(), 'Team Sports', 'Winger', 'Fullback'),
(gen_random_uuid(), 'Team Sports', 'Goalie', 'Crease'),
(gen_random_uuid(), 'Team Sports', 'Referee', 'Whistle'),
(gen_random_uuid(), 'Team Sports', 'Umpire', 'Strike'),
(gen_random_uuid(), 'Team Sports', 'Coach', 'Clipboard'),
(gen_random_uuid(), 'Team Sports', 'Captain', 'Armband'),
(gen_random_uuid(), 'Team Sports', 'Substitute', 'Bench'),
(gen_random_uuid(), 'Team Sports', 'Timeout', 'Huddle'),
(gen_random_uuid(), 'Team Sports', 'Halftime', 'Break'),
(gen_random_uuid(), 'Team Sports', 'Overtime', 'Extra Time'),
(gen_random_uuid(), 'Team Sports', 'Playoff', 'Bracket'),
(gen_random_uuid(), 'Team Sports', 'Championship', 'Trophy'),
(gen_random_uuid(), 'Team Sports', 'MVP', 'Award'),
(gen_random_uuid(), 'Team Sports', 'Rookie', 'Draft'),
(gen_random_uuid(), 'Team Sports', 'Veteran', 'Experience'),
(gen_random_uuid(), 'Team Sports', 'All-Star', 'Selection'),
(gen_random_uuid(), 'Team Sports', 'Hall of Fame', 'Legend'),
(gen_random_uuid(), 'Hobbies', 'Reading', 'Book'),
(gen_random_uuid(), 'Hobbies', 'Writing', 'Pen'),
(gen_random_uuid(), 'Hobbies', 'Painting', 'Canvas'),
(gen_random_uuid(), 'Hobbies', 'Drawing', 'Sketch'),
(gen_random_uuid(), 'Hobbies', 'Sculpting', 'Clay'),
(gen_random_uuid(), 'Hobbies', 'Photography', 'Lens'),
(gen_random_uuid(), 'Hobbies', 'Knitting', 'Yarn'),
(gen_random_uuid(), 'Hobbies', 'Sewing', 'Needle'),
(gen_random_uuid(), 'Hobbies', 'Crocheting', 'Hook'),
(gen_random_uuid(), 'Hobbies', 'Embroidery', 'Thread'),
(gen_random_uuid(), 'Hobbies', 'Quilting', 'Patch'),
(gen_random_uuid(), 'Hobbies', 'Woodworking', 'Saw'),
(gen_random_uuid(), 'Hobbies', 'Metalworking', 'Forge'),
(gen_random_uuid(), 'Hobbies', 'Pottery', 'Wheel'),
(gen_random_uuid(), 'Hobbies', 'Glassblowing', 'Furnace'),
(gen_random_uuid(), 'Hobbies', 'Origami', 'Paper'),
(gen_random_uuid(), 'Hobbies', 'Calligraphy', 'Ink'),
(gen_random_uuid(), 'Hobbies', 'Scrapbooking', 'Album'),
(gen_random_uuid(), 'Hobbies', 'Stamp Collecting', 'Philately'),
(gen_random_uuid(), 'Hobbies', 'Coin Collecting', 'Numismatics'),
(gen_random_uuid(), 'Hobbies', 'Gardening', 'Shovel'),
(gen_random_uuid(), 'Hobbies', 'Birdwatching', 'Binoculars'),
(gen_random_uuid(), 'Hobbies', 'Stargazing', 'Telescope'),
(gen_random_uuid(), 'Hobbies', 'Astronomy', 'Constellation'),
(gen_random_uuid(), 'Hobbies', 'Cooking', 'Recipe'),
(gen_random_uuid(), 'Hobbies', 'Baking', 'Oven'),
(gen_random_uuid(), 'Hobbies', 'Brewing', 'Hops'),
(gen_random_uuid(), 'Hobbies', 'Wine Making', 'Fermentation'),
(gen_random_uuid(), 'Hobbies', 'Chess', 'Checkmate'),
(gen_random_uuid(), 'Hobbies', 'Checkers', 'King'),
(gen_random_uuid(), 'Hobbies', 'Backgammon', 'Dice'),
(gen_random_uuid(), 'Hobbies', 'Poker', 'Chips'),
(gen_random_uuid(), 'Hobbies', 'Bridge', 'Trump'),
(gen_random_uuid(), 'Hobbies', 'Magic Tricks', 'Illusion'),
(gen_random_uuid(), 'Hobbies', 'Juggling', 'Balls'),
(gen_random_uuid(), 'Hobbies', 'Yo-Yo', 'String'),
(gen_random_uuid(), 'Hobbies', 'Rubiks Cube', 'Solve'),
(gen_random_uuid(), 'Hobbies', 'Puzzle', 'Jigsaw'),
(gen_random_uuid(), 'Hobbies', 'Crossword', 'Clue'),
(gen_random_uuid(), 'Hobbies', 'Sudoku', 'Grid'),
(gen_random_uuid(), 'Hobbies', 'Video Games', 'Controller'),
(gen_random_uuid(), 'Hobbies', 'Board Games', 'Dice'),
(gen_random_uuid(), 'Hobbies', 'Card Games', 'Deck'),
(gen_random_uuid(), 'Hobbies', 'Collecting', 'Action Figures'),
(gen_random_uuid(), 'Hobbies', 'Model Building', 'Glue'),
(gen_random_uuid(), 'Hobbies', 'RC Cars', 'Remote'),
(gen_random_uuid(), 'Hobbies', 'Drones', 'Quadcopter'),
(gen_random_uuid(), 'Hobbies', 'Kite Flying', 'Wind'),
(gen_random_uuid(), 'Hobbies', 'Frisbee', 'Disc'),
(gen_random_uuid(), 'Hobbies', 'Geocaching', 'GPS'),
(gen_random_uuid(), 'Hobbies', 'Metal Detecting', 'Treasure'),
(gen_random_uuid(), 'Music', 'Guitar', 'Strings'),
(gen_random_uuid(), 'Music', 'Piano', 'Keys'),
(gen_random_uuid(), 'Music', 'Drums', 'Stick'),
(gen_random_uuid(), 'Music', 'Violin', 'Bow'),
(gen_random_uuid(), 'Music', 'Trumpet', 'Brass'),
(gen_random_uuid(), 'Music', 'Saxophone', 'Reed'),
(gen_random_uuid(), 'Music', 'Flute', 'Woodwind'),
(gen_random_uuid(), 'Music', 'Clarinet', 'Mouthpiece'),
(gen_random_uuid(), 'Music', 'Trombone', 'Slide'),
(gen_random_uuid(), 'Music', 'Tuba', 'Bass'),
(gen_random_uuid(), 'Music', 'Harmonica', 'Blow'),
(gen_random_uuid(), 'Music', 'Accordion', 'Squeeze'),
(gen_random_uuid(), 'Music', 'Banjo', 'Bluegrass'),
(gen_random_uuid(), 'Music', 'Ukulele', 'Hawaiian'),
(gen_random_uuid(), 'Music', 'Harp', 'Pluck'),
(gen_random_uuid(), 'Music', 'Cello', 'Bow'),
(gen_random_uuid(), 'Music', 'Bass', 'Low'),
(gen_random_uuid(), 'Music', 'Synthesizer', 'Electronic'),
(gen_random_uuid(), 'Music', 'DJ', 'Turntable'),
(gen_random_uuid(), 'Music', 'Microphone', 'Sing'),
(gen_random_uuid(), 'Music', 'Speaker', 'Amplifier'),
(gen_random_uuid(), 'Music', 'Headphones', 'Audio'),
(gen_random_uuid(), 'Music', 'Concert', 'Stage'),
(gen_random_uuid(), 'Music', 'Album', 'Track'),
(gen_random_uuid(), 'Music', 'Single', 'Hit'),
(gen_random_uuid(), 'Music', 'Chorus', 'Verse'),
(gen_random_uuid(), 'Music', 'Melody', 'Harmony'),
(gen_random_uuid(), 'Music', 'Rhythm', 'Beat'),
(gen_random_uuid(), 'Music', 'Tempo', 'Speed'),
(gen_random_uuid(), 'Music', 'Genre', 'Style'),
(gen_random_uuid(), 'Music', 'Rock', 'Roll'),
(gen_random_uuid(), 'Music', 'Jazz', 'Improvisation'),
(gen_random_uuid(), 'Music', 'Blues', 'Twelve Bar'),
(gen_random_uuid(), 'Music', 'Country', 'Nashville'),
(gen_random_uuid(), 'Music', 'Hip Hop', 'Rap'),
(gen_random_uuid(), 'Music', 'Pop', 'Chart'),
(gen_random_uuid(), 'Music', 'Classical', 'Orchestra'),
(gen_random_uuid(), 'Music', 'Opera', 'Aria'),
(gen_random_uuid(), 'Music', 'Reggae', 'Jamaica'),
(gen_random_uuid(), 'Music', 'Funk', 'Groove'),
(gen_random_uuid(), 'Music', 'Soul', 'Motown'),
(gen_random_uuid(), 'Music', 'EDM', 'Drop'),
(gen_random_uuid(), 'Music', 'Techno', 'Club'),
(gen_random_uuid(), 'Music', 'House', 'Beat'),
(gen_random_uuid(), 'Music', 'Dubstep', 'Wobble'),
(gen_random_uuid(), 'Music', 'Metal', 'Headbang'),
(gen_random_uuid(), 'Music', 'Punk', 'Mosh'),
(gen_random_uuid(), 'Music', 'Grunge', 'Seattle'),
(gen_random_uuid(), 'Music', 'Indie', 'Alternative'),

-- EDUCATION & CONCEPTS (400 pairs)
(gen_random_uuid(), 'Education', 'School', 'Classroom'),
(gen_random_uuid(), 'Education', 'Teacher', 'Student'),
(gen_random_uuid(), 'Education', 'Principal', 'Office'),
(gen_random_uuid(), 'Education', 'College', 'University'),
(gen_random_uuid(), 'Education', 'Professor', 'Lecture'),
(gen_random_uuid(), 'Education', 'Homework', 'Assignment'),
(gen_random_uuid(), 'Education', 'Test', 'Exam'),
(gen_random_uuid(), 'Education', 'Quiz', 'Pop Quiz'),
(gen_random_uuid(), 'Education', 'Grade', 'Report Card'),
(gen_random_uuid(), 'Education', 'Diploma', 'Graduation'),
(gen_random_uuid(), 'Education', 'Degree', 'Bachelor'),
(gen_random_uuid(), 'Education', 'Major', 'Minor'),
(gen_random_uuid(), 'Education', 'Semester', 'Quarter'),
(gen_random_uuid(), 'Education', 'Curriculum', 'Syllabus'),
(gen_random_uuid(), 'Education', 'Textbook', 'Chapter'),
(gen_random_uuid(), 'Education', 'Notebook', 'Notes'),
(gen_random_uuid(), 'Education', 'Pencil', 'Eraser'),
(gen_random_uuid(), 'Education', 'Pen', 'Ink'),
(gen_random_uuid(), 'Education', 'Backpack', 'School Bag'),
(gen_random_uuid(), 'Education', 'Locker', 'Combination'),
(gen_random_uuid(), 'Education', 'Cafeteria', 'Lunch'),
(gen_random_uuid(), 'Education', 'Library', 'Books'),
(gen_random_uuid(), 'Education', 'Laboratory', 'Experiment'),
(gen_random_uuid(), 'Education', 'Gymnasium', 'PE'),
(gen_random_uuid(), 'Education', 'Playground', 'Recess'),
(gen_random_uuid(), 'Education', 'Kindergarten', 'Preschool'),
(gen_random_uuid(), 'Education', 'Elementary', 'Primary'),
(gen_random_uuid(), 'Education', 'Middle School', 'Junior High'),
(gen_random_uuid(), 'Education', 'High School', 'Secondary'),
(gen_random_uuid(), 'Education', 'Freshman', 'Sophomore'),
(gen_random_uuid(), 'Education', 'Junior', 'Senior'),
(gen_random_uuid(), 'Education', 'Valedictorian', 'Salutatorian'),
(gen_random_uuid(), 'Education', 'Scholarship', 'Financial Aid'),
(gen_random_uuid(), 'Education', 'Tuition', 'Fee'),
(gen_random_uuid(), 'Education', 'Dormitory', 'Roommate'),
(gen_random_uuid(), 'Math', 'Addition', 'Sum'),
(gen_random_uuid(), 'Math', 'Subtraction', 'Difference'),
(gen_random_uuid(), 'Math', 'Multiplication', 'Product'),
(gen_random_uuid(), 'Math', 'Division', 'Quotient'),
(gen_random_uuid(), 'Math', 'Fraction', 'Numerator'),
(gen_random_uuid(), 'Math', 'Decimal', 'Point'),
(gen_random_uuid(), 'Math', 'Percentage', 'Percent'),
(gen_random_uuid(), 'Math', 'Algebra', 'Variable'),
(gen_random_uuid(), 'Math', 'Geometry', 'Shape'),
(gen_random_uuid(), 'Math', 'Calculus', 'Derivative'),
(gen_random_uuid(), 'Math', 'Trigonometry', 'Sine'),
(gen_random_uuid(), 'Math', 'Statistics', 'Mean'),
(gen_random_uuid(), 'Math', 'Probability', 'Chance'),
(gen_random_uuid(), 'Math', 'Equation', 'Solve'),
(gen_random_uuid(), 'Math', 'Formula', 'Theorem'),
(gen_random_uuid(), 'Math', 'Graph', 'Plot'),
(gen_random_uuid(), 'Math', 'Axis', 'Coordinate'),
(gen_random_uuid(), 'Math', 'Circle', 'Radius'),
(gen_random_uuid(), 'Math', 'Square', 'Rectangle'),
(gen_random_uuid(), 'Math', 'Triangle', 'Angle'),
(gen_random_uuid(), 'Math', 'Polygon', 'Hexagon'),
(gen_random_uuid(), 'Math', 'Sphere', 'Diameter'),
(gen_random_uuid(), 'Math', 'Cube', 'Volume'),
(gen_random_uuid(), 'Math', 'Pyramid', 'Base'),
(gen_random_uuid(), 'Math', 'Cylinder', 'Height'),
(gen_random_uuid(), 'Math', 'Cone', 'Apex'),
(gen_random_uuid(), 'Math', 'Prime Number', 'Composite'),
(gen_random_uuid(), 'Math', 'Even Number', 'Odd'),
(gen_random_uuid(), 'Math', 'Integer', 'Whole Number'),
(gen_random_uuid(), 'Math', 'Rational', 'Irrational'),
(gen_random_uuid(), 'Math', 'Exponent', 'Power'),
(gen_random_uuid(), 'Math', 'Square Root', 'Radical'),
(gen_random_uuid(), 'Math', 'Absolute Value', 'Magnitude'),
(gen_random_uuid(), 'Math', 'Infinity', 'Limit'),
(gen_random_uuid(), 'Math', 'Zero', 'Nothing'),
(gen_random_uuid(), 'Math', 'Positive', 'Negative'),
(gen_random_uuid(), 'Science', 'Biology', 'Cell'),
(gen_random_uuid(), 'Science', 'Chemistry', 'Element'),
(gen_random_uuid(), 'Science', 'Physics', 'Force'),
(gen_random_uuid(), 'Science', 'Astronomy', 'Star'),
(gen_random_uuid(), 'Science', 'Geology', 'Rock'),
(gen_random_uuid(), 'Science', 'Meteorology', 'Weather'),
(gen_random_uuid(), 'Science', 'Botany', 'Plant'),
(gen_random_uuid(), 'Science', 'Zoology', 'Animal'),
(gen_random_uuid(), 'Science', 'Ecology', 'Ecosystem'),
(gen_random_uuid(), 'Science', 'Genetics', 'DNA'),
(gen_random_uuid(), 'Science', 'Evolution', 'Darwin'),
(gen_random_uuid(), 'Science', 'Photosynthesis', 'Chlorophyll'),
(gen_random_uuid(), 'Science', 'Atom', 'Nucleus'),
(gen_random_uuid(), 'Science', 'Molecule', 'Compound'),
(gen_random_uuid(), 'Science', 'Proton', 'Neutron'),
(gen_random_uuid(), 'Science', 'Electron', 'Charge'),
(gen_random_uuid(), 'Science', 'Periodic Table', 'Mendeleev'),
(gen_random_uuid(), 'Science', 'Acid', 'Base'),
(gen_random_uuid(), 'Science', 'pH', 'Neutral'),
(gen_random_uuid(), 'Science', 'Catalyst', 'Reaction'),
(gen_random_uuid(), 'Science', 'Oxidation', 'Reduction'),
(gen_random_uuid(), 'Science', 'Solid', 'Liquid'),
(gen_random_uuid(), 'Science', 'Gas', 'Plasma'),
(gen_random_uuid(), 'Science', 'Evaporation', 'Condensation'),
(gen_random_uuid(), 'Science', 'Freezing', 'Melting'),
(gen_random_uuid(), 'Science', 'Boiling', 'Vaporization'),
(gen_random_uuid(), 'Science', 'Gravity', 'Weight'),
(gen_random_uuid(), 'Science', 'Mass', 'Matter'),
(gen_random_uuid(), 'Science', 'Energy', 'Work'),
(gen_random_uuid(), 'Science', 'Kinetic', 'Potential'),
(gen_random_uuid(), 'Science', 'Momentum', 'Velocity'),
(gen_random_uuid(), 'Science', 'Acceleration', 'Speed'),
(gen_random_uuid(), 'Science', 'Friction', 'Resistance'),
(gen_random_uuid(), 'Science', 'Inertia', 'Motion'),
(gen_random_uuid(), 'Science', 'Pressure', 'Volume'),
(gen_random_uuid(), 'Science', 'Temperature', 'Heat'),
(gen_random_uuid(), 'Science', 'Light', 'Wave'),
(gen_random_uuid(), 'Science', 'Sound', 'Frequency'),
(gen_random_uuid(), 'Science', 'Electricity', 'Current'),
(gen_random_uuid(), 'Science', 'Magnetism', 'Pole'),
(gen_random_uuid(), 'Science', 'Circuit', 'Switch'),
(gen_random_uuid(), 'Science', 'Resistance', 'Ohm'),
(gen_random_uuid(), 'Science', 'Voltage', 'Ampere'),
(gen_random_uuid(), 'Science', 'Conductor', 'Insulator'),
(gen_random_uuid(), 'Science', 'Radiation', 'Radioactive'),
(gen_random_uuid(), 'Science', 'Fossil', 'Dinosaur'),
(gen_random_uuid(), 'Science', 'Earthquake', 'Seismic'),
(gen_random_uuid(), 'Science', 'Volcano', 'Magma'),
(gen_random_uuid(), 'Science', 'Tornado', 'Funnel'),
(gen_random_uuid(), 'Science', 'Hurricane', 'Eye'),
(gen_random_uuid(), 'Science', 'Tsunami', 'Tidal Wave'),
(gen_random_uuid(), 'Science', 'Eclipse', 'Solar'),
(gen_random_uuid(), 'Science', 'Planet', 'Orbit'),
(gen_random_uuid(), 'Science', 'Moon', 'Satellite'),
(gen_random_uuid(), 'Science', 'Sun', 'Star'),
(gen_random_uuid(), 'Science', 'Galaxy', 'Milky Way'),
(gen_random_uuid(), 'Science', 'Black Hole', 'Singularity'),
(gen_random_uuid(), 'Science', 'Comet', 'Tail'),
(gen_random_uuid(), 'Science', 'Asteroid', 'Meteor'),
(gen_random_uuid(), 'Science', 'Constellation', 'Orion'),
(gen_random_uuid(), 'Abstract Concepts', 'Love', 'Heart'),
(gen_random_uuid(), 'Abstract Concepts', 'Hate', 'Anger'),
(gen_random_uuid(), 'Abstract Concepts', 'Joy', 'Happiness'),
(gen_random_uuid(), 'Abstract Concepts', 'Sadness', 'Tears'),
(gen_random_uuid(), 'Abstract Concepts', 'Fear', 'Phobia'),
(gen_random_uuid(), 'Abstract Concepts', 'Hope', 'Wish'),
(gen_random_uuid(), 'Abstract Concepts', 'Dream', 'Sleep'),
(gen_random_uuid(), 'Abstract Concepts', 'Nightmare', 'Terror'),
(gen_random_uuid(), 'Abstract Concepts', 'Memory', 'Remember'),
(gen_random_uuid(), 'Abstract Concepts', 'Forget', 'Amnesia'),
(gen_random_uuid(), 'Abstract Concepts', 'Truth', 'Honesty'),
(gen_random_uuid(), 'Abstract Concepts', 'Lie', 'Deception'),
(gen_random_uuid(), 'Abstract Concepts', 'Justice', 'Fairness'),
(gen_random_uuid(), 'Abstract Concepts', 'Freedom', 'Liberty'),
(gen_random_uuid(), 'Abstract Concepts', 'Equality', 'Rights'),
(gen_random_uuid(), 'Abstract Concepts', 'Peace', 'Harmony'),
(gen_random_uuid(), 'Abstract Concepts', 'War', 'Battle'),
(gen_random_uuid(), 'Abstract Concepts', 'Victory', 'Win'),
(gen_random_uuid(), 'Abstract Concepts', 'Defeat', 'Loss'),
(gen_random_uuid(), 'Abstract Concepts', 'Success', 'Achievement'),
(gen_random_uuid(), 'Abstract Concepts', 'Failure', 'Mistake'),
(gen_random_uuid(), 'Abstract Concepts', 'Pride', 'Arrogance'),
(gen_random_uuid(), 'Abstract Concepts', 'Humility', 'Modest'),
(gen_random_uuid(), 'Abstract Concepts', 'Courage', 'Bravery'),
(gen_random_uuid(), 'Abstract Concepts', 'Cowardice', 'Fear'),
(gen_random_uuid(), 'Abstract Concepts', 'Wisdom', 'Knowledge'),
(gen_random_uuid(), 'Abstract Concepts', 'Ignorance', 'Stupidity'),
(gen_random_uuid(), 'Abstract Concepts', 'Intelligence', 'Brain'),
(gen_random_uuid(), 'Abstract Concepts', 'Creativity', 'Imagination'),
(gen_random_uuid(), 'Abstract Concepts', 'Inspiration', 'Muse'),
(gen_random_uuid(), 'Abstract Concepts', 'Motivation', 'Drive'),
(gen_random_uuid(), 'Abstract Concepts', 'Ambition', 'Goal'),
(gen_random_uuid(), 'Abstract Concepts', 'Patience', 'Wait'),
(gen_random_uuid(), 'Abstract Concepts', 'Impatience', 'Rush'),
(gen_random_uuid(), 'Abstract Concepts', 'Kindness', 'Compassion'),
(gen_random_uuid(), 'Abstract Concepts', 'Cruelty', 'Mean'),
(gen_random_uuid(), 'Abstract Concepts', 'Generosity', 'Charity'),
(gen_random_uuid(), 'Abstract Concepts', 'Greed', 'Selfish'),
(gen_random_uuid(), 'Abstract Concepts', 'Jealousy', 'Envy'),
(gen_random_uuid(), 'Abstract Concepts', 'Trust', 'Faith'),
(gen_random_uuid(), 'Abstract Concepts', 'Betrayal', 'Traitor'),
(gen_random_uuid(), 'Abstract Concepts', 'Loyalty', 'Faithful'),
(gen_random_uuid(), 'Abstract Concepts', 'Honesty', 'Integrity'),
(gen_random_uuid(), 'Abstract Concepts', 'Deceit', 'Fraud'),
(gen_random_uuid(), 'Abstract Concepts', 'Guilt', 'Shame'),
(gen_random_uuid(), 'Abstract Concepts', 'Innocence', 'Pure'),
(gen_random_uuid(), 'Abstract Concepts', 'Forgiveness', 'Pardon'),
(gen_random_uuid(), 'Abstract Concepts', 'Revenge', 'Vengeance'),
(gen_random_uuid(), 'Abstract Concepts', 'Mercy', 'Compassion'),
(gen_random_uuid(), 'Abstract Concepts', 'Beauty', 'Aesthetics'),
(gen_random_uuid(), 'Abstract Concepts', 'Ugly', 'Hideous'),
(gen_random_uuid(), 'Abstract Concepts', 'Strength', 'Power'),
(gen_random_uuid(), 'Abstract Concepts', 'Weakness', 'Fragile'),
(gen_random_uuid(), 'Abstract Concepts', 'Health', 'Wellness'),
(gen_random_uuid(), 'Abstract Concepts', 'Sickness', 'Disease'),
(gen_random_uuid(), 'Abstract Concepts', 'Life', 'Birth'),
(gen_random_uuid(), 'Abstract Concepts', 'Death', 'Grave'),
(gen_random_uuid(), 'Abstract Concepts', 'Infinity', 'Endless'),
(gen_random_uuid(), 'Abstract Concepts', 'Eternity', 'Forever'),
(gen_random_uuid(), 'Abstract Concepts', 'Destiny', 'Fate'),
(gen_random_uuid(), 'Abstract Concepts', 'Luck', 'Chance'),
(gen_random_uuid(), 'Abstract Concepts', 'Miracle', 'Wonder'),
(gen_random_uuid(), 'Abstract Concepts', 'Magic', 'Spell'),
(gen_random_uuid(), 'Abstract Concepts', 'Mystery', 'Enigma'),
(gen_random_uuid(), 'Abstract Concepts', 'Secret', 'Hidden'),
(gen_random_uuid(), 'Abstract Concepts', 'Privacy', 'Confidential'),
(gen_random_uuid(), 'Abstract Concepts', 'Chaos', 'Disorder'),
(gen_random_uuid(), 'Abstract Concepts', 'Order', 'Structure'),
(gen_random_uuid(), 'Abstract Concepts', 'Balance', 'Equilibrium'),
(gen_random_uuid(), 'Abstract Concepts', 'Harmony', 'Symphony'),
(gen_random_uuid(), 'Abstract Concepts', 'Conflict', 'Dispute'),
(gen_random_uuid(), 'Abstract Concepts', 'Agreement', 'Consensus'),
(gen_random_uuid(), 'Abstract Concepts', 'Unity', 'Together'),
(gen_random_uuid(), 'Abstract Concepts', 'Division', 'Split'),
(gen_random_uuid(), 'Abstract Concepts', 'Change', 'Transform'),
(gen_random_uuid(), 'Abstract Concepts', 'Stability', 'Constant'),
(gen_random_uuid(), 'Abstract Concepts', 'Growth', 'Development'),
(gen_random_uuid(), 'Abstract Concepts', 'Decay', 'Rot'),
(gen_random_uuid(), 'Abstract Concepts', 'Progress', 'Advancement'),
(gen_random_uuid(), 'Abstract Concepts', 'Regression', 'Backward'),
(gen_random_uuid(), 'Abstract Concepts', 'Future', 'Tomorrow'),
(gen_random_uuid(), 'Abstract Concepts', 'Past', 'History'),
(gen_random_uuid(), 'Abstract Concepts', 'Present', 'Now'),
(gen_random_uuid(), 'Abstract Concepts', 'Time', 'Clock'),
(gen_random_uuid(), 'Abstract Concepts', 'Space', 'Universe'),
(gen_random_uuid(), 'Abstract Concepts', 'Reality', 'Existence'),
(gen_random_uuid(), 'Abstract Concepts', 'Illusion', 'Mirage'),
(gen_random_uuid(), 'Abstract Concepts', 'Perception', 'Awareness'),
(gen_random_uuid(), 'Abstract Concepts', 'Consciousness', 'Mind'),
(gen_random_uuid(), 'Abstract Concepts', 'Subconsciousness', 'Unconscious'),
(gen_random_uuid(), 'Abstract Concepts', 'Thought', 'Idea'),
(gen_random_uuid(), 'Abstract Concepts', 'Emotion', 'Feeling'),
(gen_random_uuid(), 'Abstract Concepts', 'Instinct', 'Intuition'),
(gen_random_uuid(), 'Abstract Concepts', 'Logic', 'Reason'),
(gen_random_uuid(), 'Abstract Concepts', 'Faith', 'Belief'),
(gen_random_uuid(), 'Abstract Concepts', 'Doubt', 'Uncertainty'),
(gen_random_uuid(), 'Abstract Concepts', 'Certainty', 'Sure'),
(gen_random_uuid(), 'Abstract Concepts', 'Possibility', 'Maybe'),
(gen_random_uuid(), 'Abstract Concepts', 'Impossibility', 'Never'),
(gen_random_uuid(), 'Abstract Concepts', 'Probability', 'Likely'),

-- ENTERTAINMENT & MEDIA (400 pairs)
(gen_random_uuid(), 'Movies', 'Actor', 'Actress'),
(gen_random_uuid(), 'Movies', 'Director', 'Film'),
(gen_random_uuid(), 'Movies', 'Producer', 'Studio'),
(gen_random_uuid(), 'Movies', 'Screenplay', 'Script'),
(gen_random_uuid(), 'Movies', 'Camera', 'Cinematography'),
(gen_random_uuid(), 'Movies', 'Action', 'Thriller'),
(gen_random_uuid(), 'Movies', 'Comedy', 'Funny'),
(gen_random_uuid(), 'Movies', 'Drama', 'Tragedy'),
(gen_random_uuid(), 'Movies', 'Horror', 'Scary'),
(gen_random_uuid(), 'Movies', 'Romance', 'Love Story'),
(gen_random_uuid(), 'Movies', 'SciFi', 'Futuristic'),
(gen_random_uuid(), 'Movies', 'Fantasy', 'Magic'),
(gen_random_uuid(), 'Movies', 'Western', 'Cowboy'),
(gen_random_uuid(), 'Movies', 'Musical', 'Song'),
(gen_random_uuid(), 'Movies', 'Animation', 'Cartoon'),
(gen_random_uuid(), 'Movies', 'Documentary', 'Real'),
(gen_random_uuid(), 'Movies', 'Blockbuster', 'Hit'),
(gen_random_uuid(), 'Movies', 'Indie', 'Independent'),
(gen_random_uuid(), 'Movies', 'Sequel', 'Prequel'),
(gen_random_uuid(), 'Movies', 'Remake', 'Reboot'),
(gen_random_uuid(), 'Movies', 'Franchise', 'Series'),
(gen_random_uuid(), 'Movies', 'Trailer', 'Preview'),
(gen_random_uuid(), 'Movies', 'Premiere', 'Opening'),
(gen_random_uuid(), 'Movies', 'Box Office', 'Revenue'),
(gen_random_uuid(), 'Movies', 'Oscar', 'Academy Award'),
(gen_random_uuid(), 'Movies', 'Emmy', 'Television'),
(gen_random_uuid(), 'Movies', 'Golden Globe', 'Award'),
(gen_random_uuid(), 'Movies', 'Red Carpet', 'Gala'),
(gen_random_uuid(), 'Movies', 'Popcorn', 'Theater'),
(gen_random_uuid(), 'Movies', 'IMAX', 'Screen'),
(gen_random_uuid(), 'Movies', '3D', 'Glasses'),
(gen_random_uuid(), 'Movies', 'Subtitles', 'Closed Captions'),
(gen_random_uuid(), 'Movies', 'Credits', 'Cast'),
(gen_random_uuid(), 'Movies', 'Plot', 'Story'),
(gen_random_uuid(), 'Movies', 'Twist', 'Surprise'),
(gen_random_uuid(), 'Movies', 'Climax', 'Peak'),
(gen_random_uuid(), 'Movies', 'Resolution', 'Ending'),
(gen_random_uuid(), 'Movies', 'Cliffhanger', 'Suspense'),
(gen_random_uuid(), 'Movies', 'Flashback', 'Memory'),
(gen_random_uuid(), 'Movies', 'Montage', 'Sequence'),
(gen_random_uuid(), 'TV Shows', 'Sitcom', 'Laugh Track'),
(gen_random_uuid(), 'TV Shows', 'Soap Opera', 'Melodrama'),
(gen_random_uuid(), 'TV Shows', 'Reality TV', 'Unscripted'),
(gen_random_uuid(), 'TV Shows', 'Talk Show', 'Host'),
(gen_random_uuid(), 'TV Shows', 'Game Show', 'Prize'),
(gen_random_uuid(), 'TV Shows', 'News', 'Anchor'),
(gen_random_uuid(), 'TV Shows', 'Weather', 'Forecast'),
(gen_random_uuid(), 'TV Shows', 'Sports', 'Commentator'),
(gen_random_uuid(), 'TV Shows', 'Cooking Show', 'Chef'),
(gen_random_uuid(), 'TV Shows', 'Travel Show', 'Adventure'),
(gen_random_uuid(), 'TV Shows', 'Nature Documentary', 'Wildlife'),
(gen_random_uuid(), 'TV Shows', 'Crime Drama', 'Detective'),
(gen_random_uuid(), 'TV Shows', 'Medical Drama', 'Hospital'),
(gen_random_uuid(), 'TV Shows', 'Legal Drama', 'Courtroom'),
(gen_random_uuid(), 'TV Shows', 'Police Show', 'Cop'),
(gen_random_uuid(), 'TV Shows', 'Spy Thriller', 'Espionage'),
(gen_random_uuid(), 'TV Shows', 'Superhero', 'Cape'),
(gen_random_uuid(), 'TV Shows', 'Zombie', 'Apocalypse'),
(gen_random_uuid(), 'TV Shows', 'Vampire', 'Twilight'),
(gen_random_uuid(), 'TV Shows', 'Cartoon', 'Animation'),
(gen_random_uuid(), 'TV Shows', 'Anime', 'Japanese'),
(gen_random_uuid(), 'TV Shows', 'Episode', 'Season'),
(gen_random_uuid(), 'TV Shows', 'Pilot', 'Premiere'),
(gen_random_uuid(), 'TV Shows', 'Finale', 'Last Episode'),
(gen_random_uuid(), 'TV Shows', 'Cliffhanger', 'Next Season'),
(gen_random_uuid(), 'TV Shows', 'Cancellation', 'Renewal'),
(gen_random_uuid(), 'TV Shows', 'Marathon', 'Binge Watch'),
(gen_random_uuid(), 'TV Shows', 'Rerun', 'Repeat'),
(gen_random_uuid(), 'TV Shows', 'Syndication', 'Reruns'),
(gen_random_uuid(), 'TV Shows', 'Commercial', 'Advertisement'),
(gen_random_uuid(), 'TV Shows', 'Remote', 'Channel'),
(gen_random_uuid(), 'TV Shows', 'Cable', 'Satellite'),
(gen_random_uuid(), 'TV Shows', 'Streaming', 'On-Demand'),
(gen_random_uuid(), 'TV Shows', 'DVR', 'Record'),
(gen_random_uuid(), 'TV Shows', 'Live TV', 'Broadcast'),
(gen_random_uuid(), 'Gaming', 'Console', 'PlayStation'),
(gen_random_uuid(), 'Gaming', 'Xbox', 'Microsoft'),
(gen_random_uuid(), 'Gaming', 'Nintendo', 'Switch'),
(gen_random_uuid(), 'Gaming', 'PC Gaming', 'Mouse'),
(gen_random_uuid(), 'Gaming', 'Mobile Gaming', 'App'),
(gen_random_uuid(), 'Gaming', 'VR', 'Headset'),
(gen_random_uuid(), 'Gaming', 'RPG', 'Quest'),
(gen_random_uuid(), 'Gaming', 'FPS', 'Shooter'),
(gen_random_uuid(), 'Gaming', 'MMORPG', 'Online'),
(gen_random_uuid(), 'Gaming', 'Strategy', 'Tactics'),
(gen_random_uuid(), 'Gaming', 'Platformer', 'Jump'),
(gen_random_uuid(), 'Gaming', 'Puzzle', 'Brain Teaser'),
(gen_random_uuid(), 'Gaming', 'Racing', 'Track'),
(gen_random_uuid(), 'Gaming', 'Sports Game', 'FIFA'),
(gen_random_uuid(), 'Gaming', 'Fighting', 'Combo'),
(gen_random_uuid(), 'Gaming', 'Survival', 'Craft'),
(gen_random_uuid(), 'Gaming', 'Sandbox', 'Minecraft'),
(gen_random_uuid(), 'Gaming', 'Battle Royale', 'Fortnite'),
(gen_random_uuid(), 'Gaming', 'MOBA', 'League of Legends'),
(gen_random_uuid(), 'Gaming', 'Esports', 'Tournament'),
(gen_random_uuid(), 'Gaming', 'Streamer', 'Twitch'),
(gen_random_uuid(), 'Gaming', 'Level', 'Stage'),
(gen_random_uuid(), 'Gaming', 'Boss', 'Final Battle'),
(gen_random_uuid(), 'Gaming', 'Health Bar', 'HP'),
(gen_random_uuid(), 'Gaming', 'Mana', 'Magic Points'),
(gen_random_uuid(), 'Gaming', 'Experience', 'XP'),
(gen_random_uuid(), 'Gaming', 'Level Up', 'Upgrade'),
(gen_random_uuid(), 'Gaming', 'Achievement', 'Trophy'),
(gen_random_uuid(), 'Gaming', 'Leaderboard', 'Ranking'),
(gen_random_uuid(), 'Gaming', 'Multiplayer', 'Co-op'),
(gen_random_uuid(), 'Gaming', 'PvP', 'Player vs Player'),
(gen_random_uuid(), 'Gaming', 'NPC', 'Non-Player'),
(gen_random_uuid(), 'Gaming', 'Respawn', 'Revive'),
(gen_random_uuid(), 'Gaming', 'Save Point', 'Checkpoint'),
(gen_random_uuid(), 'Gaming', 'Inventory', 'Items'),
(gen_random_uuid(), 'Gaming', 'Loot', 'Treasure'),
(gen_random_uuid(), 'Gaming', 'Weapon', 'Sword'),
(gen_random_uuid(), 'Gaming', 'Armor', 'Shield'),
(gen_random_uuid(), 'Gaming', 'Potion', 'Health'),
(gen_random_uuid(), 'Gaming', 'Spell', 'Magic'),
(gen_random_uuid(), 'Gaming', 'Character', 'Avatar'),
(gen_random_uuid(), 'Gaming', 'Customization', 'Skin'),
(gen_random_uuid(), 'Gaming', 'DLC', 'Expansion'),
(gen_random_uuid(), 'Gaming', 'Patch', 'Update'),
(gen_random_uuid(), 'Gaming', 'Bug', 'Glitch'),
(gen_random_uuid(), 'Gaming', 'Lag', 'Ping'),
(gen_random_uuid(), 'Gaming', 'Rage Quit', 'Frustration'),
(gen_random_uuid(), 'Gaming', 'Noob', 'Beginner'),
(gen_random_uuid(), 'Gaming', 'Pro', 'Expert'),
(gen_random_uuid(), 'Gaming', 'Speedrun', 'Fast'),
(gen_random_uuid(), 'Social Media', 'Facebook', 'Meta'),
(gen_random_uuid(), 'Social Media', 'Instagram', 'Photo'),
(gen_random_uuid(), 'Social Media', 'Twitter', 'Tweet'),
(gen_random_uuid(), 'Social Media', 'TikTok', 'Video'),
(gen_random_uuid(), 'Social Media', 'Snapchat', 'Streak'),
(gen_random_uuid(), 'Social Media', 'YouTube', 'Subscribe'),
(gen_random_uuid(), 'Social Media', 'LinkedIn', 'Professional'),
(gen_random_uuid(), 'Social Media', 'Pinterest', 'Board'),
(gen_random_uuid(), 'Social Media', 'Reddit', 'Subreddit'),
(gen_random_uuid(), 'Social Media', 'Tumblr', 'Blog'),
(gen_random_uuid(), 'Social Media', 'WhatsApp', 'Chat'),
(gen_random_uuid(), 'Social Media', 'Telegram', 'Messenger'),
(gen_random_uuid(), 'Social Media', 'Discord', 'Server'),
(gen_random_uuid(), 'Social Media', 'Slack', 'Workspace'),
(gen_random_uuid(), 'Social Media', 'Influencer', 'Content Creator'),
(gen_random_uuid(), 'Social Media', 'Viral', 'Trending'),
(gen_random_uuid(), 'Social Media', 'Algorithm', 'Feed'),
(gen_random_uuid(), 'Social Media', 'Engagement', 'Interaction'),
(gen_random_uuid(), 'Social Media', 'Analytics', 'Insights'),
(gen_random_uuid(), 'Social Media', 'Follower', 'Subscriber'),
(gen_random_uuid(), 'Social Media', 'Post', 'Content'),
(gen_random_uuid(), 'Social Media', 'Story', '24 Hours'),
(gen_random_uuid(), 'Social Media', 'Reels', 'Short Video'),
(gen_random_uuid(), 'Social Media', 'Live', 'Broadcast'),
(gen_random_uuid(), 'Social Media', 'Collaboration', 'Partnership'),
(gen_random_uuid(), 'Social Media', 'Sponsored', 'Paid'),
(gen_random_uuid(), 'Social Media', 'Cancel Culture', 'Backlash'),
(gen_random_uuid(), 'Social Media', 'Meme', 'Viral'),
(gen_random_uuid(), 'Social Media', 'GIF', 'Reaction'),
(gen_random_uuid(), 'Social Media', 'Emoji', 'Smiley'),
(gen_random_uuid(), 'Books', 'Novel', 'Chapter'),
(gen_random_uuid(), 'Books', 'Author', 'Writer'),
(gen_random_uuid(), 'Books', 'Publisher', 'Editor'),
(gen_random_uuid(), 'Books', 'Bestseller', 'Popular'),
(gen_random_uuid(), 'Books', 'Fiction', 'Imaginary'),
(gen_random_uuid(), 'Books', 'Non-Fiction', 'Factual'),
(gen_random_uuid(), 'Books', 'Biography', 'Life Story'),
(gen_random_uuid(), 'Books', 'Autobiography', 'Memoir'),
(gen_random_uuid(), 'Books', 'Mystery', 'Detective'),
(gen_random_uuid(), 'Books', 'Thriller', 'Suspense'),
(gen_random_uuid(), 'Books', 'Romance', 'Love'),
(gen_random_uuid(), 'Books', 'Fantasy', 'Dragons'),
(gen_random_uuid(), 'Books', 'SciFi', 'Aliens'),
(gen_random_uuid(), 'Books', 'Historical Fiction', 'Past'),
(gen_random_uuid(), 'Books', 'Young Adult', 'Teen'),
(gen_random_uuid(), 'Books', 'Children', 'Picture Book'),
(gen_random_uuid(), 'Books', 'Poetry', 'Verse'),
(gen_random_uuid(), 'Books', 'Essay', 'Article'),
(gen_random_uuid(), 'Books', 'Textbook', 'Study'),
(gen_random_uuid(), 'Books', 'Encyclopedia', 'Reference'),
(gen_random_uuid(), 'Books', 'Dictionary', 'Definition'),
(gen_random_uuid(), 'Books', 'Atlas', 'Maps'),
(gen_random_uuid(), 'Books', 'Cookbook', 'Recipe'),
(gen_random_uuid(), 'Books', 'Self-Help', 'Improvement'),
(gen_random_uuid(), 'Books', 'Comic Book', 'Graphic Novel'),
(gen_random_uuid(), 'Books', 'Manga', 'Japanese'),
(gen_random_uuid(), 'Books', 'eBook', 'Digital'),
(gen_random_uuid(), 'Books', 'Audiobook', 'Narration'),
(gen_random_uuid(), 'Books', 'Hardcover', 'Paperback'),
(gen_random_uuid(), 'Books', 'Bookmark', 'Page'),
(gen_random_uuid(), 'Books', 'Library', 'Borrow'),
(gen_random_uuid(), 'Books', 'Bookstore', 'Shop'),
(gen_random_uuid(), 'Books', 'Reading', 'Comprehension'),
(gen_random_uuid(), 'Books', 'Plot', 'Storyline'),
(gen_random_uuid(), 'Books', 'Character', 'Protagonist'),
(gen_random_uuid(), 'Books', 'Setting', 'Location'),
(gen_random_uuid(), 'Books', 'Theme', 'Message'),
(gen_random_uuid(), 'Books', 'Conflict', 'Problem'),
(gen_random_uuid(), 'Books', 'Resolution', 'Solution'),
(gen_random_uuid(), 'Books', 'Dialogue', 'Conversation'),
(gen_random_uuid(), 'Books', 'Narration', 'Description'),
(gen_random_uuid(), 'Books', 'Prologue', 'Introduction'),
(gen_random_uuid(), 'Books', 'Epilogue', 'Conclusion'),
(gen_random_uuid(), 'Books', 'Sequel', 'Continuation'),
(gen_random_uuid(), 'Books', 'Trilogy', 'Three Books'),
(gen_random_uuid(), 'Books', 'Series', 'Collection'),
(gen_random_uuid(), 'Books', 'Anthology', 'Compilation'),
(gen_random_uuid(), 'Books', 'Adaptation', 'Movie'),
(gen_random_uuid(), 'Books', 'Review', 'Critique'),
(gen_random_uuid(), 'Books', 'Recommendation', 'Suggest'),

-- PROFESSIONS & CAREERS (300 pairs)
(gen_random_uuid(), 'Professions', 'Doctor', 'Stethoscope'),
(gen_random_uuid(), 'Professions', 'Nurse', 'Scrubs'),
(gen_random_uuid(), 'Professions', 'Surgeon', 'Operating Room'),
(gen_random_uuid(), 'Professions', 'Dentist', 'Drill'),
(gen_random_uuid(), 'Professions', 'Pharmacist', 'Prescription'),
(gen_random_uuid(), 'Professions', 'Veterinarian', 'Animals'),
(gen_random_uuid(), 'Professions', 'Lawyer', 'Court'),
(gen_random_uuid(), 'Professions', 'Judge', 'Gavel'),
(gen_random_uuid(), 'Professions', 'Police Officer', 'Badge'),
(gen_random_uuid(), 'Professions', 'Firefighter', 'Hose'),
(gen_random_uuid(), 'Professions', 'Paramedic', 'Ambulance'),
(gen_random_uuid(), 'Professions', 'Teacher', 'Chalk'),
(gen_random_uuid(), 'Professions', 'Professor', 'University'),
(gen_random_uuid(), 'Professions', 'Engineer', 'Blueprint'),
(gen_random_uuid(), 'Professions', 'Architect', 'Building'),
(gen_random_uuid(), 'Professions', 'Carpenter', 'Wood'),
(gen_random_uuid(), 'Professions', 'Plumber', 'Pipe'),
(gen_random_uuid(), 'Professions', 'Electrician', 'Wire'),
(gen_random_uuid(), 'Professions', 'Mechanic', 'Wrench'),
(gen_random_uuid(), 'Professions', 'Chef', 'Kitchen'),
(gen_random_uuid(), 'Professions', 'Baker', 'Bread'),
(gen_random_uuid(), 'Professions', 'Waiter', 'Tray'),
(gen_random_uuid(), 'Professions', 'Bartender', 'Cocktail'),
(gen_random_uuid(), 'Professions', 'Barista', 'Coffee'),
(gen_random_uuid(), 'Professions', 'Farmer', 'Tractor'),
(gen_random_uuid(), 'Professions', 'Fisherman', 'Net'),
(gen_random_uuid(), 'Professions', 'Pilot', 'Cockpit'),
(gen_random_uuid(), 'Professions', 'Flight Attendant', 'Cabin'),
(gen_random_uuid(), 'Professions', 'Astronaut', 'Spaceship'),
(gen_random_uuid(), 'Professions', 'Scientist', 'Laboratory'),
(gen_random_uuid(), 'Professions', 'Researcher', 'Study'),
(gen_random_uuid(), 'Professions', 'Chemist', 'Beaker'),
(gen_random_uuid(), 'Professions', 'Biologist', 'Microscope'),
(gen_random_uuid(), 'Professions', 'Physicist', 'Particle'),
(gen_random_uuid(), 'Professions', 'Mathematician', 'Equation'),
(gen_random_uuid(), 'Professions', 'Programmer', 'Code'),
(gen_random_uuid(), 'Professions', 'Software Developer', 'Application'),
(gen_random_uuid(), 'Professions', 'Web Designer', 'Website'),
(gen_random_uuid(), 'Professions', 'Graphic Designer', 'Photoshop'),
(gen_random_uuid(), 'Professions', 'Artist', 'Paintbrush'),
(gen_random_uuid(), 'Professions', 'Sculptor', 'Chisel'),
(gen_random_uuid(), 'Professions', 'Photographer', 'Camera'),
(gen_random_uuid(), 'Professions', 'Videographer', 'Camcorder'),
(gen_random_uuid(), 'Professions', 'Film Director', 'Action'),
(gen_random_uuid(), 'Professions', 'Producer', 'Studio'),
(gen_random_uuid(), 'Professions', 'Musician', 'Instrument'),
(gen_random_uuid(), 'Professions', 'Singer', 'Microphone');

